### ISSUE TITLE
Minor position issue on Manager dashboard - iPhone with Safari

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1022]
On iPhone default dashboard has the welcome panel in the wrong position . It is not top left but further down after the recently edited panel.

This just seems to be a Safari browser issue as it is fine with Crhome on the same phone.

Edit - also just found the small icons that shrink/expand the left site tree and top menu do not work.

![you_doodle_2016-11-30t16_25_42z](https://cloud.githubusercontent.com/assets/1744687/20761098/d124cfcc-b719-11e6-82d9-307dcebbcf18.jpg)

**Comment by Nicola1971** [comment]
not sure (i dont have an iphone, i will try with ipad) but should be this error in welcome.tpl:
https://github.com/modxcms/evolution/pull/1025

Dashboard is a four column grid, the second widget on the right should be placed on 3rd
column, not on 2nd column.
Actually User Info and Security news widgets are on the second column instead third column. 
Could cause this issue, because the second widget deals half of space of the first widget

**Comment by bossloper** [comment]
Yes looks like your last pull request fixes it.
