### ISSUE TITLE
Feature Request: Automatic Scheduled Snapshots

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#1028]
Hello,

Just a feature request...

The recent security issue highlights the need for scheduled database backups.

The current "Backup Snapshot" feature is excellent and very easy to use.

It would be even more so if this could be extended to include automatic scheduled snapshots:
eg
choose backup schedule: daily, every second day, every third day, weekly, fortnightly etc
choose backup time: time picker
choose how many snapshots to keep on the server: 10, 15, 20, unlimited
plus maybe choose whether to send download link: an email is sent after successful backup with a download link
plus maybe choose whether to send to remote storage: eg dropbox

Doing something like this within the Backup snapshot (or the standard Backup) would be great.

I don't know how to do cron jobs so to be able to set up a backup schedule within Evo would be awesome.

Thanks and keep up the great work.

**Comment by Deesen** [comment]
We can also improve the bkmanager to allow doing tar.gz-backups of a whole MODX-installation. I already wrote my own "backupper"-script to easily backup a whole webspace incl all SQL-databases into the target-archive. It requires the server to have permission to run PHP´s `exec()` as well as `/bin/tar`, and enough `max_execution_time`, otherwise files will be missing in the archive and backup is incomplete without anybody noticing it.

This way I do not have to download webspace file by file but just create a compressed tar.gz-archive of everything and download it.

**Comment by Deesen** [comment]
A PHP-oriented CRON-mechanismn for future versions was also already proposed by @bossloper and @yama in some other issue.

**Comment by nick0** [comment]
Thanks @Deesen, that sounds promising. 

Something that works straight from the Evo manager would be awesome.

**Comment by Nicola1971** [comment]
Automatic EvoBackup on system events

https://github.com/Nicola1971/AutoEvoBackup

**Comment by nick0** [comment]
Thanks @Nicola1971, I can't wait to check this out next week. Cheers so much
