### ISSUE TITLE
Configuration error if editor include files missing.

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#1060]
If during the upgrade, delete the folder with the old tinimce, after installation in the configuration get the error.

It is clear that the removal of outdated plugin tinimce is help - then you can set in the configuration new tinmce4.

I think that would prevent it, as well as other possible problems with corruption files used when calling the configuration, it is necessary to set check it, end remove from choice of editor.

?

**Comment by Deesen** [comment]
Same principle/issue as with PHx? 

@yama @dmi3yy Just brainstorming: Maybe an Ajax-driven script in installprocessor can add a pre-check of all plugins first? This way we should be able to get around / catch any fatal-errors. So browser sends an ajax-request per plugin to eval() its code. If no eval()-error, the script returns just "plugin_ok", otherwise it will return the error-message directly.

This way the Ajax-script can create a list of failed plugins. Then the script can disable all error-causing plugins when proceeding with installation.

**Comment by yama** [comment]
Since there are various plug-ins in the world, it is uneasy to actually execute. I feel that unexpected problems may occur.
https://github.com/modxcms-jp/evolution-jp/blob/develop/manager/includes/accesscontrol.inc.php
How about the ideas like the above?
Please track the string "$ touch_path". 
"garbage file" remains when execution fails at the time of actual use, not at the time of installation. By looking at the name of this "garbage file", we can know that it is an invalid plugin.
Invalid plugins can be found in the event log.

**Comment by yama** [comment]
When creating a file, it is a bit disadvantageous to take load. Perhaps it's not so smart.
It is necessary to think about the balance as to how much such trouble actually exists. I think the balance is bad for excessive implementation.

**Comment by yama** [comment]
https://github.com/modxcms-jp/evolution-jp/blob/develop/manager/includes/accesscontrol.inc.php
Just for reference
For example, if the login screen disappears due to a plugin that customizes the login screen. This process invalidates that plugin for 5 minutes.

**Comment by Deesen** [comment]
So if 2 plugins fail (phx, old tinymce), it would be nessecary to reload settings-page 2x to disable plugins one by one and then have all settings-tabs available?

**Comment by yama** [comment]
> to reload settings-page

Yes. If there is an intuitive message there. For example, "Please correct the setting within 5 minutes".

**Comment by Deesen** [comment]
From my understanding it makes sense and will possibly cover also future issues.

**Comment by dmi3yy** [comment]
test  tinymce3  + tinymce4 work togeter

**Comment by Deesen** [comment]
In MODX-Settings? Because using v3 + v4 simultaneously on the same "Edit Resource"-page is not possible by TinyMCE-core.

**Comment by dmi3yy** [comment]
i think this can be close 

if you delete  tinymce3 but not delete plugin, you get error like any other plugin with files)
