### ISSUE TITLE
tinymce4 inline edit   -> alert: secHash invalid, and dont save

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1067]
<div class="editable" id="modx_content">[*#content*]</div>
и 
<div class="editable" id="modx_content">[*content*]</div>

**Comment by Deesen** [comment]
Strange, there was important code missing. Also this fix is not complete, you will loose content when clicking save because of https://github.com/modxcms/evolution/blob/develop/assets/lib/MODxAPI/modResource.php#L555

To make inline-edit working again we need to remove ` || (!$this->newDoc && $this->isChanged($key))` or change it. Not sure yet what is happening there.

**Comment by dmi3yy** [comment]
fix dont save

**Comment by Deesen** [comment]
Is server-access possible for me to see?

**Comment by dmi3yy** [comment]
all ok

**Comment by Deesen** [comment]
For others who eventually have problems, first assure you have latest files installed

    assets/plugins/tinymce4/bridge.tinymce4.inc.php
    assets/lib/MODxAPI/modResource.php
    assets/lib/class.modxRTEbridge.php
