### ISSUE TITLE
Manage Elements / Combinded Veiw

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1091]
When viewing elements in "Combined View" via "Manage Elements", `uncategorized` elements are not displayed.

**Comment by modxuser** [comment]
Same here, don't see it either

**Comment by Nicola1971** [comment]
i can confirm: uncategorized elements are not displayed in Combined View.

1. I checked an old beta, before latest mods on Manage Elements (icons, filter search), same issue - no uncategorized elements.
2.  so i checked an Evo 1.1pl - same here!!! no uncategorized elements
3. then, checked 1.0.15 - no issue here, i can see uncategorized elements 

it's a 1.0/1.1 issue never discovered before :)

personally i don't care much about it, because i'm waiting for better category management with evo 1.2.2:
https://github.com/modxcms/evolution/pull/851

**Comment by Nicola1971** [comment]
it is possible that someone has intentionally removed uncategorized elements from this tab, i don't know
