### ISSUE TITLE
Manager resources - stale lock build up

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1119]
Manager locks on resources can still build up when a manager closes a browser without cancelling an edit.

1. Edit a resource
2. Close the browser window while still editing the resource
3. Open browser back up - resource still shows locked and will be locked unless edited again and cancelled or a proper manager 'logout' is done.
4. if this is repeated then many resources can be locked.

I was of the assumption from the mechanism described here https://github.com/modxcms/evolution/issues/945#issuecomment-262496391 that 'old' locks that were outside the 'Session Timeout' interval would be automatically removed. If so then this does not appear to be working for resources. Elements seem fine in that as soon as the browser is closed while editing an element the lock is removed.

**Comment by Deesen** [comment]
I have investigated this issue extensively and it seems there is no way around it. I already used [navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) to try to catch the unload-event and send unlock-requests as relyable as possible. But it seems it does not work as one would expect because:

Any events like unload-, beforeunload, pagehide-events etc will NOT be triggered at tab- or window-close. Simply because of the fact UI, javascript-engine etc are shut-down immediately. sendBeacon or SJAX-requests (synchronous AJAX) will be only made as long as leaving the tab/popup-window open, when user leaves the page for whatever reason. That is the case for me with Chrome and Firefox.

They will also not get fired when typing new URL into browser and pressing enter.

**Comment by bossloper** [comment]
Hmmm, then I'd have to suggest that the locking is returned to how it worked before so that editing a new resource removes any previous locks otherwise on a large site there will be many more locked resources over time for managers that are in the habit of just closing the browser. Also the logout_reminder_msg only really seams to kick in if logging in from from a different browser type so it does not help reduce the problem of locks.

**Comment by Deesen** [comment]
Most of the big players like Joomla etc support multiple locks. And they insist on pressing a close-key, otherwise elements stay locked. But admins can unlock with a click on the lock-icon. We are more modern, providing sendBeacon to catch some events. I am not sure if the old mechanismn is up to date.

Any expired locks will get removed if you log in with a different user. The cleanup-function does not remove locks of the actually logged-in user who calls it.

**Comment by bossloper** [comment]
If "Any expired locks will get removed if you log in with a different user." is working correctly then great. I'll do a few more tests over the weekend.

p.s. I did open up a browser this morning and have an element lock showing with no date. No idea the specific scenario yet:

![untitled](https://cloud.githubusercontent.com/assets/1744687/21286052/82daad0c-c441-11e6-9881-8e5838577aab.png)

**Comment by Deesen** [comment]
I am not sure why the placeholder will not be replaced but I fixed those irritating remaining locks. Expired locks will now also be removed for same user at login.

**Comment by bossloper** [comment]
Nice. I'll give it a test later today...

**Comment by bossloper** [comment]
One last thing on this. In the settings it says "MODX will ping the server once every minute". 
Is that minute the 'Mail check time period' value? If so it is not always necessarily 1 minute. Plus does that mean the Session timeout value needs to always be >= to the 'mail check time period'?

![untitled](https://cloud.githubusercontent.com/assets/1744687/21307810/09845428-c5cf-11e6-91b7-528dbaec8e90.png)

**Comment by Deesen** [comment]
Thanks, good catch.. I have already prepared a fix "on save settings" to assure session-timeout is at least +1min compared to mail check time period.

**Comment by bossloper** [comment]
I think this is all complete now so closing...
