### ISSUE TITLE
File manager rename files

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1124]
I would like to have the option to rename files in the File Manager. Would that be possible?

**Comment by dmi3yy** [comment]
Rename and dublicate

Отправлено с iPhone

**Comment by Deesen** [comment]
@Nicola1971 Maybe for rename there is a better icon? I took the "reply"-icon.

![rename](https://cloud.githubusercontent.com/assets/8569221/21302557/36408426-c5b8-11e6-9697-03381478ccae.png)

**Comment by risingisland** [comment]
For Rename, what about using the "Terminal" ![fa terminal font awesome icons](https://cloud.githubusercontent.com/assets/6113504/21306078/1dff3e66-c5c7-11e6-8425-8de00f613b38.png) or "Eraser" ![fa eraser font awesome icons](https://cloud.githubusercontent.com/assets/6113504/21306089/28369bea-c5c7-11e6-9b35-2b591792f13e.png) icon?

**Comment by fourroses666** [comment]
Or the pencil?
http://fontawesome.io/icon/pencil/

**Comment by Nicola1971** [comment]
@Deesen not easy :(

@risingisland 
* Terminal: should be ok, but i think arrow looks too much like the one used for unordered list 
* eraser: It can be confused with a delete action

@fourroses666 
* pencil: It's ok, but can be confused with the edit button

maybe

http://fontawesome.io/icon/i-cursor/
http://fontawesome.io/icon/magic/
http://fontawesome.io/icon/text-width/ 
http://fontawesome.io/icon/font/

the best should be a mix with: http://fontawesome.io/icon/font/ and http://fontawesome.io/icon/i-cursor/ to get something like this: 

![stock-vector-rename-icon-248900827](https://cloud.githubusercontent.com/assets/7342798/21309517/f0787fee-c5de-11e6-88f4-3280affc1617.jpg)

**Comment by pmfx** [comment]
Cursor or mix looks OK.

**Comment by Deesen** [comment]
I like the mix too :+1:

**Comment by fourroses666** [comment]
Or use T from text instead of A. 
_Ans a line around it?_

**Comment by Nicola1971** [comment]
@Deesen wait 1-2 days, because I'm almost finished some layout refactoring on File Manager and replaced all images icons with Font Awesome. need just some styling 
![ji1vk laaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21404376/34822a76-c7c1-11e6-94a1-47937ea2a562.png)

**Comment by Nicola1971** [comment]
ok, done
![nk3hf9gcgaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21427717/7b2d463c-c856-11e6-8f59-176aae92d84a.png)

**Comment by dmi3yy** [comment]
Nice
Maybe add Odd even background ?


От 22 декабря 2016 г. в 15:55:02, Nicola (notifications@github.com) написал:

ok, done
[image: nk3hf9gcgaaaaaelftksuqmcc]
<https://cloud.githubusercontent.com/assets/7342798/21427717/7b2d463c-c856-11e6-8f59-176aae92d84a.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1124#issuecomment-268804110>,
or mute the thread

**Comment by Nicola1971** [comment]
@dmi3yy 
> Maybe add Odd even background ?

tested, but all rows backgrouds returns to white bg after mouse over - i think it's a conflict with some js

**Comment by fourroses666** [comment]
if that won't work, maybe 1px bottom border #e2e2e2;

**Comment by Nicola1971** [comment]
updated a bit with button aligned on right

![whvrgbjnhhlygaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/21434657/02f633a2-c876-11e6-9c73-2aee0f89e7d7.png)

@fourroses666 @pmfx 

not sure about icons colour
On latest MODxRE2 we have two icons colours:

![wbhcmiibmehyaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/21434726/58299d28-c876-11e6-84b8-4760eb5f65f8.png)

![k2cquyffgv43dk 9boxxyaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/21434743/5bbfc156-c876-11e6-8171-7c95bcc48efc.png)


should be the same

**Comment by fourroses666** [comment]
The darker blue-ish color was for readability.
I'm oke with color change either way. Don't know what looks the best and whats the easiest to change.

**Comment by Nicola1971** [comment]
agree, should be all darker blue, not grey

**Comment by Nicola1971** [comment]
![5pvklx9hpiwaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21452794/b3dd3326-c909-11e6-895d-7e876c7953e5.png)


but i dont like very much folders and page icons (too much smaller and barely clear :(

**Comment by Nicola1971** [comment]
![4qbwzcgvt96b0rt3bfjb4wresxozgzdgillykj51ihh0hbkkyraairaairaairaairaapfdycjc1f8bsfhloiorw8eaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/21453325/1fcbdfb6-c90e-11e6-946a-a59cbbc7bb1f.png)

**Comment by dmi3yy** [comment]
Icons maybe like in tree? Same color?


От 23 декабря 2016 г. в 13:48:55, Nicola (notifications@github.com) написал:

[image:
4qbwzcgvt96b0rt3bfjb4wresxozgzdgillykj51ihh0hbkkyraairaairaairaairaapfdycjc1f8bsfhloiorw8eaaaaasuvork5cyii]
<https://cloud.githubusercontent.com/assets/7342798/21453325/1fcbdfb6-c90e-11e6-946a-a59cbbc7bb1f.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1124#issuecomment-268979030>,
or mute the thread

**Comment by Nicola1971** [comment]
![f d3oil3bwjfwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/21453420/1920077c-c90f-11e6-9522-94d8c72796ad.png)


anyway, now is much more customizable with styles :)

**Comment by dmi3yy** [comment]
Great )
More better  I think its can pull in 1.2.1 ))



От 23 декабря 2016 г. в 13:57:34, Nicola (notifications@github.com) написал:

[image: f d3oil3bwjfwaaaabjru5erkjggg]
<https://cloud.githubusercontent.com/assets/7342798/21453420/1920077c-c90f-11e6-9522-94d8c72796ad.png>

anyway, now is much more customizable with styles :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1124#issuecomment-268979939>,
or mute the thread

**Comment by Nicola1971** [comment]
i've tried to add a **sorting on columns**, should be nice sort files from name, size and modified date (to check hacked files or whatever), but **tablesort.js** (included in evo) does not sort well sizes and dates (sorts by the first number) :(

**Comment by dmi3yy** [comment]
Ок )


От 23 декабря 2016 г. в 14:01:48, Nicola (notifications@github.com) написал:

i've tried to add a *sorting on columns*, should be nice sort files from
name, size and modified date (to check hacked files or whatever), but
*tablesort.js* (included in evo) does not sort well sizes and dates (sorts
by the first number) :(

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1124#issuecomment-268980389>,
or mute the thread

**Comment by Nicola1971** [comment]
@dmi3yy , before pull , there is an hardcoded text "This directory is empty."
need to replace with a new language sting?

**Comment by dmi3yy** [comment]
Yes )


От 23 декабря 2016 г. в 14:06:41, Nicola (notifications@github.com) написал:

@dmi3yy <https://github.com/dmi3yy> , before pull , there is an hardcoded
text "This directory is empty."
need to replace with a new language sting?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1124#issuecomment-268980888>,
or mute the thread
