### ISSUE TITLE
CONFUSED: 1.0.13 RCxx

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1138]
@dmi3yy 

I  have just seen numerous release candidates 1.0.13 RCx

Are they supposed to be 1.2.1 RCx ?

**Comment by dmi3yy** [comment]
I orders suggests tags to make it correct for the plug-in updates
and the date for broken :(

Today i  will release 1.2.1RC

От 24 декабря 2016 г. в 13:41:33, modxuser (notifications@github.com)
написал:

@dmi3yy <https://github.com/dmi3yy>

I have just seen numerous release candidates 1.0.13 RCx

Are they supposed to be 1.2.1 RCx ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1138>, or mute the thread

**Comment by dmi3yy** [comment]
Fixed )

**Comment by modxuser** [comment]
Thanks - sorry for the late reply Xmas and all that :)
