### ISSUE TITLE
Security: PHPMailer vulnerability

### ISSUE THREAD

**Issue by hquadrat** [modxcms/evolution#1155]
Hi guys,

I hope this is no duplicate: has this issue already been adressed/taken care of?
[https://legalhackers.com/advisories/PHPMailer-Exploit-Remote-Code-Exec-CVE-2016-10033-Vuln.html](https://legalhackers.com/advisories/PHPMailer-Exploit-Remote-Code-Exec-CVE-2016-10033-Vuln.html)

Maybe PHPMailer is not part of Evo and so there is no problem, so please close then.

Regards,

Henning

**Comment by dmi3yy** [comment]
I Update 28.12.2016 )

realise will be 02.01.2017


От 29 декабря 2016 г. в 15:08:33, HQuadratIT (notifications@github.com)
написал:

Hi guys,

I hope this is no duplicate: has this issue already been adressed/taken
care of?
https://legalhackers.com/advisories/PHPMailer-Exploit-Remote-Code-Exec-CVE-2016-10033-Vuln.html

Maybe PHPMailer is not part of Evo and so there is no problem, so please
close then.

Regards,

Henning

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1155>, or mute the thread

**Comment by hquadrat** [comment]
Thank you for taking care!
