### ISSUE TITLE
Dashboard remove button

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1162]
Would it be cool to have a remove button for the dashboard items.
We now only can + or -

Or some dashboard settings where to choose what to show or not?

**Comment by fourroses666** [comment]
Missed your reply. 
Hmmm, Its cool but I don't want to install the plugin on every site I have.
Don't know if others care much. 

Settings icon on the dashboard next to reset.

**Comment by Nicola1971** [comment]
anyway, i have done theclose button, some times ago in my various dashboards tests: works, but only for your localstorage

**Comment by Nicola1971** [comment]
found - done in october a test:
https://www.youtube.com/watch?v=m7YyDeH2guY

**Comment by fourroses666** [comment]
What I like to achive is; don't show "News" and "Safety warnings" for any client (and admin).
Also for some clients don't show last login. So localstorage would be no use.
But if there is no need for this I can install the plugin.

**Comment by fourroses666** [comment]
I like it Nicola.

Couple of settings I don't understand or use. Like the logo path (deprecated maybe?)

- Looks like when using the plugin it has its own dashboard.css file.
.widget-wrapper .widget-title is font-weight:200 while needs 300 so guess its not the same as latest from MODXRE2.
- Some extra padding to align the footer (reset) would be nice.
- Maybe you can add a setting Remove inbox messages?
- The width of the first welcome column would look better if its 50% ?

**Comment by Nicola1971** [comment]
@fourroses666 

> Looks like when using the plugin it has its own dashboard.css file.
.widget-wrapper .widget-title is font-weight:200 while needs 300 so guess its not the same as latest from MODXRE2.

You can set Theme styles from ***Use theme styles*** from plugin config but the feature was  broken in dev branch: - fixed now in master (and merged to 1.2.1 from dev)
I added this option to support old themes without dashboard. I will change to **yes** - to be the default settings. 
![dashboard-manager-styles](https://cloud.githubusercontent.com/assets/7342798/22156504/d338b502-df33-11e6-9e68-c43eee98b478.png)


> Maybe you can add a setting Remove/hide inbox messages?

With 1.2 was not possible, but with latest yama changes i can do :)


> The width of the first welcome column would look better if its 50% ?

not understood which column? UserInfo table inside Welcome widget?

> Multilang?

Reset button is Multilanguage, For now there are not other strings to translate

**Comment by Nicola1971** [comment]
fixed a couple of small bugs and added option to hide messages

**Comment by fourroses666** [comment]
Just updated, leaving the office now! 

This I mean: 50% looks better :o its fixed width?!

![yo](https://cloud.githubusercontent.com/assets/523389/22158062/c35495be-df3a-11e6-96f0-6fcd401f3b4c.jpg)

**Comment by Nicola1971** [comment]
understand, but I'm using the same used as default in Evo
https://github.com/modxcms/evolution/blob/develop/manager/actions/welcome.static.php#L145
do you need an option to set the cell width? 

>  I don't understand or use. Like the logo path (deprecated maybe?)

I's an option to restore  logo+sitename in the dashboard (removed/deprecated in 1.2 to save space)

But, after a check, i've just fixed the default path in the plugin config, because there is no more assets/images/logo.png (it's recently replaced with assets/images/modx-logo.png)
![logo-dash](https://cloud.githubusercontent.com/assets/7342798/22162240/1bb797b6-df4e-11e6-9086-9edeeefe823b.png)

You can use a custom logo (ie: the customer logo) and show/hide the title (show only the custom logo)
![custom-logo](https://cloud.githubusercontent.com/assets/7342798/22162374/c62dae4c-df4e-11e6-81a5-ec5bdb07065a.png)
