### ISSUE TITLE
MODX 1.2 and the migration to TinyMCE4

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/evolution#1199]
Can the upgrade process automatically switch the 'Editor to use' selector from TinyMCE3 to 4, not only in the main Config Settings but also for each User?

Obviously if the value is set to anything other than TinyMCE3 then it should not be touched.

**Comment by nick0** [comment]
I noticed this too just yesterday. 

In Manage Users > Create/Edit User...

The setting for File Browser has the Default option selected for me. The 2 options are Default and mcpuk.

Whereas in Editor to Use nothing is selected (its a blank row). The 3 options are Blank, None or TinyMCE4. I think Default (should be on by default if nothing else saved I think so that it uses whatever setting is saved in the config), None or TinyMCE4.

Wouldn't it be better still to just have TinyMCE - not the version number. Otherwise isn't this something we will have to tweak when TinyMCE5 comes along and so on in each update?

**Comment by Deesen** [comment]
> Wouldn't it be better still to just have TinyMCE

I think no because some people may want to stay with Tiny3, 4 or 5 even after updates. And some probably dont want to loose their configuration etc, which also changes from version to version.

**Comment by nick0** [comment]
That makes sense. But then in this instance I lost those settings anyway as things had moved and TinyMCE was not on by default in 1.2.1.

**Comment by modxuser** [comment]
@ricardo-lewis If this issue is resolved can you close it please, if you are not sure how to, take a [look here](https://github.com/modxcms/evolution/issues/1213)

**Comment by Deesen** [comment]
@nick0 Most probably settings are not compatible between different versions. After update at least you have Tiny3 in your plugins-list, so you can check its configuration and try to convert it into your new Tiny4-config.

**Comment by ricardo-lewis** [comment]
I'm happy to close the issue, my problem is that MODX deactivated TinyMCE3 but it didn't seem smart enough to change the value of the selected RTE to the correct replacement – TinyMCE4. It just left the system with a null value and that was causing genuine problems.
