### ISSUE TITLE
Phpthumb crop is off 1 pixel?!

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1255]
On my site I crop images to 500px width but there is one image thats 499 px wide.
When you set 500 width it should be 500 with!
Also on an other site the same result. Never experienced that before. (yes original is larger)

Cropped = 499 and not 500px width!
http://www.vtt.esensdev2.nl/assets/cache/images/in-beeld/wagenpark/500x320-vantieltransport-wagenpark-04.f82.jpg

Original:
http://www.vtt.esensdev2.nl/assets/images/in-beeld/wagenpark/vantieltransport-wagenpark-04.jpg

I use MultiTV to preview the images:
```<img src="[[phpthumb? &input=`[+image+]` &options=`w=500,h=320,zc=1`]]" width="500" height="320" alt="" />```

Gives issues with float:left alignment :(

**Comment by Deesen** [comment]
I just found that posting of Mark Hamstra who mentioned they use Imagine now instead of phpThumb: "Using Imagine additionally fixed an old rounding issue with images of certain dimensions, where the generated image would be off by 1px. "

https://forum.modmore.com/t/moregallery-under-the-hood-changes/372

What happens if you change dimensions of original image slightly, maybe it will be rounded differently then?
