### ISSUE TITLE
Not work Sibling: the same Template as other Resources in the same container.

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1279]
http://take.ms/taRQY	

http://take.ms/JdGLq
	http://take.ms/VgGdc
	http://take.ms/3k1Jj

**Comment by dmi3yy** [comment]
tested now all ok

**Comment by Deesen** [comment]
I tried to recreate this issue but I do not understand completely. Everything´s working here as expected.

My test:

- creating resource "Parent 3" in (83) will choose right template "parent"
- creating resource "Child 4" in (85) will choose right template "child"
- creating **first** resource inside "Parent 1" will choose the "default" template, because no siblings to provide any other

![issue-1279-tree](https://cloud.githubusercontent.com/assets/8569221/24322719/27094b7a-116a-11e7-96ca-ea8b8362b07f.png)

**Comment by dmi3yy** [comment]
> creating first resource inside "Parent 1" will choose the "default" template, because no siblings to provide any other

Its not correct 

If no siblings use not default use parent template. 



Отправлено с iPhone

**Comment by dmi3yy** [comment]
On russian lang Write:
 Соседний: такой же шаблон, как у соседних ресурсов в этом контейнере (если соседних ресурсов нет, шаблон Родитель).

If translate: 

Neighbor: the same template as the neighboring resources in this container (if there are no neighboring resources, the parent template).




Отправлено с iPhone
