### ISSUE TITLE
Теряются ТВ-параметры при сохранении шаблона

### ISSUE THREAD

**Issue by liber87** [modxcms/evolution#1288]
Если работать с шаблоном, а на второй вкладке создать ТВ и привязать к текущему шаблону, то при сохранении шаблона новый ТВ "отвязывается"...

**Comment by Deesen** [comment]
In english: If you work with the template, and on the second tab create a TV and bind to the current template, then when you save the template, the new TV is "untied" ...

**Comment by dmi3yy** [comment]
Ну дык логично все:)
обсуждалось уже раз 5

так как во второй  вкладке шаблона теперь можно привязывать ТВ )
потому одно другому мешаеmn

но текущий функционал куда как правктиченей ио можно привязать больше 1 ТВ
сразу )


От 27 марта 2017 г. в 10:03:05, liber87 (notifications@github.com) написал:

Если работать с шаблоном, а на второй вкладке создать ТВ и привязать к
текущему шаблону, то при сохранении шаблона новый ТВ "отвязывается"...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1288>, or mute the thread

**Comment by dmi3yy** [comment]
fixed
