### ISSUE TITLE
Logged in and going from www. to non www. manager

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1293]
It doesn't occur allot but I noticed when I'm logged into the manager with www. and going to the manager without www. then have to log in again and when logged in I get the following screen.
(FF on Mac)

For this site I'm on Evo 1.2.1 RC2 (and YAMS)

When deleting the /assets/cache/siteHostnames.idx.php file its ok again.

![www](https://cloud.githubusercontent.com/assets/523389/24493289/a2cf5836-152e-11e7-89c6-782fd7401f23.jpg)

**Comment by dmi3yy** [comment]
Fix in hostManager   in assets/cache/.  or in setting allow hosts


От 30 марта 2017 г. в 10:57:09, Marc (notifications@github.com) написал:

It doesn't occur allot but I noticed when I'm logged into the manager with
www. and going to the manager without www. then have to log in again and
when logged in I get the following screen.
(FF on Mac)

For this site I'm on Evo 1.2.1 RC2 (and YAMS)

When deleting the /assets/cache/siteHostnames.idx.php file its ok again.

[image: www]
<https://cloud.githubusercontent.com/assets/523389/24493289/a2cf5836-152e-11e7-89c6-782fd7401f23.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1293>, or mute the thread

**Comment by dmi3yy** [comment]
for browser. www anв no www diferent sites ) 
use .htaccess for  redirect and all be or   in hostManager  add 2 hosts
