### ISSUE TITLE
AliasListing только для Папок

### ISSUE THREAD

**Issue by scorN17** [modxcms/evolution#1298]
При включении "AliasListing только для Папок" в Конфигурации появляется такая проблема:
при формировании ссылки на ресурс не учитываются галочки "Участвует в URL" - такие ресурсы система прописывает в адресе ссылки.

Например:
Есть структура:
1. Категория [page1] - галочка "Участвует в URL" снята
1.1. Подкатегория [page11] - галочка "Участвует в URL" стоит

Нажимаю у ресурса "page11" на кнопку "Просмотр"
- открывается вкладка со страницей: /page1/page11/

Если "AliasListing только для Папок" - "Нет"
- ссылка: /page11/

**Comment by dmi3yy** [comment]
Нельзя выключать последнего родителя из URL так как тогда в aliasListing нет вообще информации о паренте и получаем кучу головняка. Уже сталкивался с этим но пока адекватного решения не нашел так что б исправляло все ошибки

**Comment by sunhaim** [comment]
Но ведь я предлагал фикс #1232, и его приняли.
Он не исправляет ссылку при нажатии на кнопку "Просмотр", но корректно обработает вторую /page11/.

**Comment by dmi3yy** [comment]
Там появляется проблема что можно подставить людую другую папку :) и все
равно отобразиться нужный документ


От 10 апреля 2017 г. в 14:09:39, sunhaim (notifications@github.com) написал:

Но ведь я предлагал фикс #1232
<https://github.com/modxcms/evolution/pull/1232>, и его приняли.
Он не исправляет ссылку при нажатии на кнопку "Просмотр", но корректно
обработает вторую /page11/.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1298#issuecomment-292919363>,
or mute the thread

**Comment by sunhaim** [comment]
Хм, потестирую этот момент позже

**Comment by sunhaim** [comment]
Имеете в виду, подставить в ссылку, например /kfdgsdhger/page11/ ?

**Comment by dmi3yy** [comment]
Ага


От 10 апреля 2017 г. в 14:14:30, sunhaim (notifications@github.com) написал:

Имеете в виду, подставить в ссылку, например /kfdgsdhger/page11/ ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1298#issuecomment-292920292>,
or mute the thread

**Comment by sunhaim** [comment]
Потестировал: срабатывает либо путь без скрытых ресурсов (/page11/), либо полный путь (/page1/page11). Любые другие варианты не работают.
Причем makeUrl работает правильно, т.е. убирает все скрытые ресурсы из ссылки.
У меня дистрибутив времен начала года, может в этом дело.
http://testing-modx.mishka.perm.ru/g1.html

**Comment by dmi3yy** [comment]
Тестить надо на последней версии


От 10 апреля 2017 г. в 14:35:26, sunhaim (notifications@github.com) написал:

Потестировал: срабатывает либо путь без скрытых ресурсов (/page11/), либо
полный путь (/page1/page11). Любые другие варианты не работают.
Причем makeUrl работает правильно, т.е. убирает все скрытые ресурсы из
ссылки.
У меня дистрибутив времен начала года, может в этом дело.
http://testing-modx.mishka.perm.ru/g1.html

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1298#issuecomment-292924158>,
or mute the thread

**Comment by scorN17** [comment]
Попробуй найти решение.
Наметьте "головняки", с которыми могу столкнуться, если не сложно.

**Comment by dmi3yy** [comment]
Ну вот исправить ту ошибку которая вам мешает. В целом ограничения я написал. Банально не исключать последнюю папку из ЧПУ и будет все ок
