### ISSUE TITLE
Website Search Broken Post 1.2.1 Upgrade

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1313]
I get the following Error : mysql_real_escape_string(): Access denied for user ''@'localhost' (using password: NO)

when searching from this page:  http://www.canmorerealestate.com/news.

Further details from the error can be seen here:  https://cl.ly/1d143y293s2X

And contents of the snippet blog_get_search_ditto are as follows:

``<?php
$blog_query = mysql_real_escape_string($_GET['query']);	
$modx->setPlaceholder('blog_query',$blog_query);

$id = $modx->documentIdentifier;

// Ditto parameters
$params['parents'] = '15';
$params['extenders'] = 'summary,search';
$params['tpl'] = 'blog_listing_tpl';
$params['orderBy'] = 'pub_date DESC';
$params['dateSource'] = 'pub_date';
$params['display'] = '5';
$params['truncText'] = 'Read More...';
$params['dateFormat'] = '%m/%d/%y';

$params['searchFields'] = 'content,pagetitle';
$params['searchString'] = $blog_query;
$params['searchOptions'] = '';

$params['paginate'] = '1';
$params['tplPaginatePage'] = '@CODE: <li><a href="[+url+]">[+page+]</a></li>';
$params['tplPaginateCurrentPage'] = '@CODE: <li class="current_menu_item"><a>[+page+]</a></li>';

	
$output = $modx->runSnippet('Ditto', $params);
return "$output";
``

Not sure what the cause or fix is for this one.

**Comment by dmi3yy** [comment]
change $blog_query = mysql_real_escape_string($_GET['query']);
to

$blog_query = $modx-Юви->escape($_GET['query']);



От 21 апреля 2017 г. в 18:37:07, Tourist4Life (notifications@github.com)
написал:

I get the following Error : mysql_real_escape_string(): Access denied for
user ''@'localhost' (using password: NO)

when searching from this page: http://www.canmorerealestate.com/news.

Further details from the error can be seen here: https://cl.ly/1d143y293s2X

And contents of the snippet blog_get_search_ditto are as follows:

``<?php
$blog_query = mysql_real_escape_string($_GET['query']);
$modx->setPlaceholder('blog_query',$blog_query);

$id = $modx->documentIdentifier;

// Ditto parameters
$params['parents'] = '15';
$params['extenders'] = 'summary,search';
$params['tpl'] = 'blog_listing_tpl';
$params['orderBy'] = 'pub_date DESC';
$params['dateSource'] = 'pub_date';
$params['display'] = '5';
$params['truncText'] = 'Read More...';
$params['dateFormat'] = '%m/%d/%y';

$params['searchFields'] = 'content,pagetitle';
$params['searchString'] = $blog_query;
$params['searchOptions'] = '';

$params['paginate'] = '1';
$params['tplPaginatePage'] = '@CODE <https://github.com/CODE>:

   - [+page+] <[+url+]>
   - ';
   $params['tplPaginateCurrentPage'] = '@CODE <https://github.com/CODE>:
   - [+page+]
   - ';

$output = $modx->runSnippet('Ditto', $params);
return "$output";
``

Not sure what the cause or fix is for this one.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1313>, or mute the thread

**Comment by Tourist4Life** [comment]
thanks but i get this error now: 

https://cl.ly/0h3H1I3Q1V1a

...I'm assuming that is perhaps due to a non-english keyboard ?

**Comment by dmi3yy** [comment]
$blog_query = $modx->db->escape($_GET['query']);


От 21 апреля 2017 г. в 18:54:49, Tourist4Life (notifications@github.com)
написал:

$blog_query = $modx-Юви->escape($_GET['query']);

**Comment by Tourist4Life** [comment]
Beauty!  Thank you @dmi3yy !
