### ISSUE TITLE
Cannot install snippet

### ISSUE THREAD

**Issue by MyckolaPetrychko** [modxcms/evolution#1360]
I have this error when I am trying to install Wayfinder using Extras: 

/manager/index.php?id=2&a=112&method=fast&action=install&cid=161&name=Wayfinder Failed to load resource: the server responded with a status of 500 (Internal Server Error)

I have noticed that this script is trying to download the snippet using that url: 
$url = "http://modx-store.com/get.php?get=file&cid=".$id;

But this domain doesn`t have a resource get.php.

Can anyone provide a url to errorless download a snippets?

Thank you.

Modx: 1.2.2

**Comment by dmi3yy** [comment]
Modx-store.com.   old domain now dont work


От 11 июня 2017 г. в 19:43:25, pmv (notifications@github.com) написал:

I have this error when I am trying to install Wayfinder using Extras:

/manager/index.php?id=2&a=112&method=fast&action=install&cid=161&name=Wayfinder
Failed to load resource: the server responded with a status of 500
(Internal Server Error)

I have noticed that this script is trying to download the snippet using
that url:
$url = "http://modx-store.com/get.php?get=file&cid=".$id;

But this domain doesn`t have a resource get.php.

Can anyone provide a url to errorless download a snippets?

Thank you.

Modx: 1.2.2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1360>, or mute the thread

**Comment by MyckolaPetrychko** [comment]
dmi3yy: Can you provide a url to errorless download a snippets?

**Comment by dmi3yy** [comment]
update extras will be all ok
extras.evolution-cms.com



От 11 июня 2017 г. в 19:57:44, pmv (notifications@github.com) написал:

dmi3yy: Can you provide a url to errorless download a snippets?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1360#issuecomment-307642067>,
or mute the thread

**Comment by MyckolaPetrychko** [comment]
I have downloaded an extras from url that you had provided. But it contains the same url: Modx-store.com. 
And the file update.php is looks like: 
`$url = "http://modx-store.com/get.php?get=file&cid=1";
$newfname = 'update.zip';
................`

**Comment by dmi3yy** [comment]
https://github.com/modxcms/evolution/blob/develop/assets/modules/store/core.php

От 11 июня 2017 г. в 20:11:13, pmv (notifications@github.com) написал:

I have downloaded an extras from url that you had provided. But it contains
the same url: Modx-store.com.
And the file update.php is looks like:
$url = "http://modx-store.com/get.php?get=file&cid=1"; $newfname =
'update.zip'; ................

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1360#issuecomment-307642848>,
or mute the thread

**Comment by MyckolaPetrychko** [comment]
Thank you!
