### ISSUE TITLE
docinfo, userHelper, etc.?

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1361]
@dmi3yy 
• What are all of these newly added Snippets and Plugins?
There is no info...
![new](https://user-images.githubusercontent.com/6113504/27013407-21e5893e-4edb-11e7-9e50-756b0ade1b6e.jpg)

• When installing, it shows...
![modx install](https://user-images.githubusercontent.com/6113504/27013408-21f0e86a-4edb-11e7-9a0b-9e50f9be58a6.png)

• Why is this new empty file here?
manager/media/style/common/bootstrap/css/bootstrap.min.css.map

**Comment by dmi3yy** [comment]
its ready for.  merge.  modx evolution and my custom. to new Evolution CMS

bootstrap.min.css.map - if no file all time in console  error 404 )


От 11 июня 2017 г. в 21:26:04, risingisland (notifications@github.com)
написал:

@dmi3yy <https://github.com/dmi3yy>
What are all of these newly added Snippets and Plugins?
There is no info...
[image: new]
<https://user-images.githubusercontent.com/6113504/27013407-21e5893e-4edb-11e7-9e50-756b0ade1b6e.jpg>

When installing, it shows...
[image: modx install]
<https://user-images.githubusercontent.com/6113504/27013408-21f0e86a-4edb-11e7-9a0b-9e50f9be58a6.png>

Why is this new empty file here?
manager/media/style/common/bootstrap/css/bootstrap.min.css.map

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1361>, or mute the thread
