### ISSUE TITLE
Removal of MODX brand?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1373]
Did a new install, see some nice improvements :)

There is allot of modx in the manager;
At some point we need to remove that?

![modx](https://user-images.githubusercontent.com/523389/27275379-67d71082-54d7-11e7-8612-40a0fd947979.jpg)

![modx2](https://user-images.githubusercontent.com/523389/27275380-67db2460-54d7-11e7-99f4-e7c1b25b3f4e.jpg)

![modx3](https://user-images.githubusercontent.com/523389/27275381-67dd8566-54d7-11e7-97b9-493bb9332539.jpg)

![modx4](https://user-images.githubusercontent.com/523389/27275377-67d19c92-54d7-11e7-9ca9-61935c80cb60.jpg)

----
When click on the nav icon it is small.
![nav-icon-ok](https://user-images.githubusercontent.com/523389/27275376-67d0c79a-54d7-11e7-93d7-5a45a8ddce67.png)

Blank dropdown
![ff-drop](https://user-images.githubusercontent.com/523389/27275378-67d35a6e-54d7-11e7-9aa2-417878cff99f.jpg)

![nav](https://user-images.githubusercontent.com/523389/27275643-98ecd05c-54d8-11e7-8619-cabd54a41603.jpg)

I like the dark resource tree I have seen on this image;

![slack-imgs](https://user-images.githubusercontent.com/523389/27275519-0d944972-54d8-11e7-8ae5-a853eaad376e.png)

Dark blue looks a little nicer thow;
Clients are used to the colors and see allot of wrong colors.

![theme-colors](https://user-images.githubusercontent.com/523389/27275999-f1f711ca-54d9-11e7-9712-9c045912e212.jpg)

But maybe I'm too soon with this post? 🔨

**Comment by dmi3yy** [comment]
wait some  times i commits new:

http://take.ms/KBTtO


if want test better use https://github.com/dmi3yy/modx.evo.custom/

after  ready logo. We are  rebranding to Evolution CMS and go to new repos:
https://github.com/evolutioncms

and i megre my custom and modx evo to one branch

now difference  only in settings and  default elements.
http://take.ms/7vzOE




От 19 июня 2017 г. в 11:29:29, Marc (notifications@github.com) написал:

Did a new install, see some nice improvements :)

There is allot of modx in the manager;
At some point we need to remove that?

[image: modx]
<https://user-images.githubusercontent.com/523389/27275379-67d71082-54d7-11e7-8612-40a0fd947979.jpg>

[image: modx2]
<https://user-images.githubusercontent.com/523389/27275380-67db2460-54d7-11e7-99f4-e7c1b25b3f4e.jpg>

[image: modx3]
<https://user-images.githubusercontent.com/523389/27275381-67dd8566-54d7-11e7-97b9-493bb9332539.jpg>

[image: modx4]
<https://user-images.githubusercontent.com/523389/27275377-67d19c92-54d7-11e7-9ca9-61935c80cb60.jpg>
------------------------------

When click on the nav icon it is small.
[image: nav-icon-ok]
<https://user-images.githubusercontent.com/523389/27275376-67d0c79a-54d7-11e7-93d7-5a45a8ddce67.png>

Blank dropdown
[image: ff-drop]
<https://user-images.githubusercontent.com/523389/27275378-67d35a6e-54d7-11e7-9aa2-417878cff99f.jpg>

[image: nav]
<https://user-images.githubusercontent.com/523389/27275643-98ecd05c-54d8-11e7-8619-cabd54a41603.jpg>

I like the dark resource tree I have seen on this image;

[image: slack-imgs]
<https://user-images.githubusercontent.com/523389/27275519-0d944972-54d8-11e7-8ae5-a853eaad376e.png>

Dark blue looks a little nicer thow;
Clients are used to the colors and see allot of wrong colors.

[image: theme-colors]
<https://user-images.githubusercontent.com/523389/27275999-f1f711ca-54d9-11e7-9712-9c045912e212.jpg>

But maybe I'm too soon with this post? 🔨

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1373>, or mute the thread

**Comment by fourroses666** [comment]
Just playing some with the manager (theme)

![manager-theme](https://user-images.githubusercontent.com/523389/27279289-7b41853c-54e4-11e7-8258-58cfb88cfbb7.jpg)

**Comment by risingisland** [comment]
I think many are going to have their own theme preferences.
Personally, I liked something more like the following, but to each their own...
![27011418-30587594-4eb3-11e7-9b70-bf8ac3b5be4d](https://user-images.githubusercontent.com/6113504/27283983-c294ceda-54ee-11e7-8714-d59299fe3c20.png)

**Comment by dmi3yy** [comment]
There is no problem to change the style.
Now the task is to clean all html css js
And after that there will be 1 basic theme that can be changed.

**Comment by fourroses666** [comment]
Yea, the default/basic theme must look good. 👍
