### ISSUE TITLE
eForm not working on php version 5.2

### ISSUE THREAD

**Issue by keslo** [modxcms/evolution#403]
As mentioned above, eform not working on php version 5.2. Change php version 5.3 will solve the problem.

**Comment by pmfx** [comment]
AFAIK, on http://develop.modx.com/develop/evolution/requirements/ is said that MODX requires

> PHP version 5.2-5.4 (excluding 5.2.0)
> (Some extras require at least PHP 5.3+)

Maybe it's not a bug and eForm needs 5.3 at least?

**Comment by janniconl** [comment]
Thx for reporting but this is not a bug -_- PHP 5.2.x is 9-6 years old, which is almost ancient in terms of the web ;-) Time to upgrade.

**Comment by keslo** [comment]
Most likely you're right. But I took a whole day to sort out the problem:-)

**Comment by janniconl** [comment]
Ah thats never fun :(
Apart from being hard or not, I don't think anyone here will spend time to make it work on a 9 year old version of PHP. I'm sure you can understand that. It is really advised to upgrade to a newer PHP version, because running these old versions will also expose you to various security threats (it is not supported anymore). Also see: http://bigemployee.com/stop-using-php-5-2/

**Comment by janniconl** [comment]
(p.s.: same goes for your site kanby.ru, I really advise you to upgrade to a later Modx version considering the security risks)

**Comment by keslo** [comment]
I agree.
I called customer service and I changed the version of PHP 5.2 -> 5.3. All is well.
but it took me a lot of time trying to find the cause.

May enter into eFort check for php version with a message if the version of php <5.3?

**Comment by keslo** [comment]
@janniconl thanks!

**Comment by janniconl** [comment]
Like @pmfx said, the requirements state PHP 5.3 for most extras. Not worth the time to implement messages in all extras which versions they DONT support ;-)
