### ISSUE TITLE
Major Security Issues

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#449]
Please read the post from "mrhaw" on the MODX forum: http://forums.modx.com/thread/98830/security-clippercms-public-disclosures-by-curesec-nov-2015

**Comment by mrhaw** [comment]
KP replied: http://www.clippercms.com/forum/viewtopic.php?id=331

**Comment by modxuser** [comment]
I don't think that is the point - yes, KP is right in saying that the majority of problems require an account, but, i've had sites hacked and accounts have been made by the hacker - so, the account argument isn't (IMHO) a valid argument.

It's still a matter that, in terms of the end user, should be looked at.

**Comment by mrhaw** [comment]
Yes! I posted this so it would get attention. I'm 99% migrated to Revolution and I have zero websites running ClipperCMS.

**Comment by dmi3yy** [comment]
Evo havent this bugs

**Comment by mrhaw** [comment]
Awesome! :)

**Comment by modxuser** [comment]
Great stuff - thanks for checking

**Comment by yama** [comment]
https://github.com/dmi3yy/modx.evo.custom/issues/298
All OK

**Comment by TimGS** [comment]
re: "I don't think that is the point - yes, KP is right in saying that the majority of problems require an account, but, i've had sites hacked and accounts have been made by the hacker - so, the account argument isn't (IMHO) a valid argument."

KP's point is exactly that if a user - malicious or otherwise - has an account, then they can quite obviously wreak havoc with or without this "vulnerability". They can write to the site, delete users, and in fact can do anything any other user can do. They don't need the presence or otherwise of this "issue" to do anything they want that a manager user can do.

I've only just had my attention brought to this thread, but it really isn't appreciated that misleading claims are being made about code in ClipperCMS.
