### ISSUE TITLE
Sort Menu Items

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#532]
Does it make sense to pull the 'Sort Menu Items' out of the Document Manager module and allow it to be referenced directly from the menu tree options list without needing access to 'Document Manager'?

'Sort Menu Items' is relatively harmless and many site editors would need to sort the menu tree, however the other tabs in the Document Manager are quite 'powerful', more for the site admin and not suitable for general site managers.

**Comment by pmfx** [comment]
This is a great idea.

**Comment by fourroses666** [comment]
:+1:

**Comment by Nicola1971** [comment]
:thumbsup:

**Comment by fourroses666** [comment]
Would that be a replacement of the tree or just extra option?

**Comment by bossloper** [comment]
I was envisaging just an extra option on the menu tree context menu to sort the child resources of a particular resource.

It should be 'relatively simple' and reliable, as the code has been around for a while, to copy out the sort code from DocManager to create a new action, passing in the docid to be sorted.

Do also need to ensure it honours manager access permissions.

**Comment by Deesen** [comment]
I think this makes perfect sense. Also because the "Sort menu items"-tabs is the only tab in DocManager without "Specify a Range of Document IDs".

**Comment by janniconl** [comment]
By adding an <img> tag to rule 421 of file https://github.com/Deesen/evolution/blob/0e7cfc70c80c6cde5811b95f256cf000c703dcd3/manager/frames/tree.php (the icon in the tree menubar) we can not use font-icons anymore. Please change this to `<?php echo $_style['icons_sort_menuindex']; ?>` instead of `<img src="<?php echo $_style['icons_sort_menuindex'] ; ?>" />`, just like the other icons have.

**Comment by janniconl** [comment]
Thx @Deesen !
