### ISSUE TITLE
eForm reCaptcha anti spam feature?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#541]
There are allot of sites I manage which uses eForm.
But there is so much spam being send to the clients, almost daily.
So I was thinking about some good spam protection.
It looks like the Googles reCaptcha is very strong and "easy" to manage.
https://www.google.com/recaptcha

This I would love to have as option for eForm.
The nicest would be to add the keys to the eFormcall like _&secretKey=`key-here`_

Is it something that could be a default option or don't we use/like it and it should be added "manual"?

https://forums.modx.com/thread/99706/eform---recaptcha-verification-anti-spam#dis-post-539280

![hero-recaptcha-demo](https://cloud.githubusercontent.com/assets/523389/13603853/725bae1c-e540-11e5-85c1-4ed2777f378b.gif)

**Comment by janniconl** [comment]
I have a honeypot solution, which prevents spam for all of my dozens of installations pretty well. A captcha is not needed, which is why imo this way is much more userfriendly.

This requires an extra hidden (via CSS) field in your form, which has to be EMPTY on form submit. The bots will usally fill in this hidden field. I'm using a snippet to check if this field is empty. It does not prevent the form itself being submitted, but it does not mail or process the form in any way.

Add a extra field to your form, hide it with css, it doesnt matter how you call it. Best is to make it look the same as other fields to mislead the bots, e.g.:

````
			<div class="form-group hide">
				<label class="control-label" for="yourfieldname">Do <strong>NOT</strong> fill in this field</label>
				<input id="yourfieldname" name="yourfieldname" type="text" autocomplete="off" eform="yourfieldname::0">
			</div>  
````

Css could be something like:

````
.form-group.hide {
    background-color: red;
    height: 1px;
    left: 0;
    overflow: hidden;
    position: absolute;
    text-decoration: underline;
    top: -800px;
    width: 1px;
}
````

Make a new snippet which checks the hidden field (in my case called [[checkField]])
The message shown can by anything, i've added 'Succes Mail' sent to mislead the bots.
I've also added a message for humans, just in case they see this for what every reason. 

````
<?php
function checkField(&$fields,&$vMsg,&$rMsg) {
    if(!empty($fields['yourfieldname'])) {
        echo "<p>Succes. Mail sent<br><br>Add a message here for humans who accidentally see this message.</p>";
        return false;
    } else {
    return true;
    }
}
?>
````

Run the snippet function in your Eform call:

````
[!checkField!]
[[eForm? 
    &amp;formid=`yourform` 
    &gotoid=`22`

... etc.....

    &eformOnValidate=`checkField`  
]]
````

**Comment by bossloper** [comment]
+1 for the honeypot solution, I use the same on all my sites and it seems to do the job well.

**Comment by fourroses666** [comment]
Thanks, added it to a site which keeps getting spam even thow I also used an "hidden" (date)field protection.

**Comment by janniconl** [comment]
Make it a normal text input, try changing the id/name of the field aswell. You could also use different css styles to hide it.

**Comment by fourroses666** [comment]
:+1:

**Comment by bossloper** [comment]
yes it needs to be 'normal' field, not hidden, but with css to remove it from the form. I use css: position:absolute, top:-500px
