### ISSUE TITLE
Sort by menuindex with same number

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#626]
On default the tree sorts on menu_index. This is very good.
But when, for example, a resource gets duplicated the menuindex is equal.
After saving resources the sortorder gets crazy because it doesn't know how to order this.

Can it sort on creation date (only) when the sort order is equal? So it doesn't jumps all over the place?

**Comment by modxuser** [comment]
I always hack the code to make it sort by "ID + ASC" by default

Its a pain having to reset everytime you start a session

**Comment by janniconl** [comment]
> 

On default the tree sorts on menu_index. This is very good.
But when, for example, a resource gets duplicated the menuindex is equal.
After saving resources the sortorder gets crazy because it doesn't know how to order this.

Can it sort on creation date (only) when the sort order is equal? So it doesn't jumps all over the place?

Maybe it's an idea to +1 the menuindex when duplicating a resource? For example it searches the child with the highest menu-index and then +1's it?  Or will that mess with peolpes expectations/workflows. I've struggled with this as well. I'm quite used now to +1 the menuindex when I duplicate, but ideally it shouldn't be needed imo.

**Comment by Deesen** [comment]
Reg. using additional "orderby ID asc", there is a MODX-setting "Increment Resource ID method" with options: DB auto increment, Minimum missed ID, Maximal ID + 1.

If it is set to "minimum missed ID" (why does such a setting exists?) I guess duplicates will be sorted again not like expected. So for me it makes most sense to sort additionally by "createdon" like proposed by fourroses666.

**Comment by janniconl** [comment]
Also see: http://code.divandesign.biz/modx/mm_ddfillmenuindex

**Comment by fourroses666** [comment]
https://github.com/modxcms/evolution/issues/626#issuecomment-221479587
