### ISSUE TITLE
access rights of web users and managers

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#635]
Hi, I observe a problem with the access rights of web users and managers (in admin panel)
"As the Web user groups and managers in conflict with your role, this resource will be available to all."

trivial task, to give access to the folder with the documents only to specific users.

version 1.0.15, the permanent manager of the problem of access to the files, if you include the right to access. This problem was and earlier versions

**Comment by Fr3ddyCruger** [comment]
the same problem, and on the latest version (1.1 git), the manager must initially be able to and have access to rights, but it is not.

appears only if your hands to create a group manager, group manager for documents tie it all in a bunch ... then it runs.

**Comment by Deesen** [comment]
Sry it seems I don´t understand important details. Maybe you can explain the steps to recreate that issue? Like

  - Create new webuser-group "web1"
  - Create new manager-group "mgr1"
  - Create resource-group "X"
  - ...

For developers to start: The error message $_lang['access_permissions_docs_collision'] can be found in mutate_content.dynamic.php @line 1200 and gets echoed by this statement:

    if($_SESSION['mgrRole'] != 1 && 
    ($permissions_yes == 0 && $permissions_no > 0) &&
    ($_SESSION['mgrPermissions']['access_permissions'] == 1 ||
     $_SESSION['mgrPermissions']['web_access_permissions'] == 1)
    )

**Comment by Fr3ddyCruger** [comment]
task has a folder with the documents to which access web users (different groups and different access)

folder = 1 Web User 1
 - Document 1
 - Document 2
folder 2 = web user 2
 - Document 1
 - Document 2
folder 3 = web user 3
 - Document 1
 - Document 2

the problem lies elsewhere, a manager may not display the right, though, and should have a "managerial access" without adding to the group.

everything starts to work, if the manager to make a group, the group of documents and link all this + and then put in the document access manager group.

otherwise produces text at the bottom of the page:
"As the Web user groups and managers in conflict with your role, this resource will be available to all."

**Comment by Fr3ddy7** [comment]
http://modx.im/blog/addons/4970.html
