### ISSUE TITLE
multiple file drag upload and gif, png background black problem

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#663]
Hi,
When I drag and upload multiple images , they all change to like this
eg 1.jpg change to 1.jpg, 1(1),jpg , 1(2),jpg . so it change to three file for one images, 

And I can't upload gif and png format, I don't know why . they all have black background.
Hosting - Digital Ocean (Ubuntu 14.04)
Modx version - 1.1

**Comment by mgzawlinoo** [comment]
I test with modx version - 1.0.14 
no problem with multiple upload and gif, png black background.

**Comment by mgzawlinoo** [comment]
![kcfinder images plywood smartborad gypsumborad](https://cloud.githubusercontent.com/assets/9032715/16563633/27f5b962-4229-11e6-9225-4fda6179f485.png)

**Comment by mgzawlinoo** [comment]
just like that , when I drag 4 or more photos and upload . They will automatically change to triple files.

**Comment by mgzawlinoo** [comment]
gif, png thumb background change to black 
resize png background chagne to black . But I disable resize image function at modx setting and it's solve . Please help me to fix the code?

**Comment by mgzawlinoo** [comment]
Problem solve , 
I copy mcpuk folder from 1.0.15 and replace . Problem solve .

**Comment by Deesen** [comment]
Maybe you want to reopen the issue so we can solve it for 1.1.1 ?

**Comment by mgzawlinoo** [comment]
Thz deesen , I'm replace old version mcpuk , black background (png,gif) problem solve . But still have drag upload when I upload more than 5 images.

**Comment by Nicola1971** [comment]
Same issue for me with 1.1, but i have multiple copies of the same image , even when i upload a single image with drag and drop

**Comment by Deesen** [comment]
I tested it with MODX´s logo.png and v1.1. I renamed the image to logo2.png and uploaded it via drag´n´drop using Firefox & Chrome. Also tested multiple files. Result: Only 1 copy per file, and the background is also correct. So everything works like expected on 1 installation so far for me?

**Comment by janniconl** [comment]
I have the same problems on my 1.1.1 installations. Although only one server with the multiple upload problem.

**Server 1: just black images problem, for PNGs**
Specs:
PHP Version:	 	5.3.5
Database:	 	5.1.53
Modx: 1.1.1 latest dev
Chrome: latest version

![transp1](https://cloud.githubusercontent.com/assets/1488614/16578020/9a780502-4298-11e6-97c3-f1beb5b46cc7.png)

I think the problem here is that the thumbnails are generated as .JPG, while the source image is .PNG

Possible solutions/similar issues:
http://stackoverflow.com/questions/19953600/php-thumb-resize-png-image-but-add-black-background
https://github.com/masterexploder/PHPThumb/issues/58

Maybe make thumbnails PNG when source is PNG? Of just set the background to white when converting PNG to JPG?

**Server 2: black images problem, for PNGs + upload issue**
Specs:
PHP Version:	 	5.6.22
Database:	 	5.5.5-10.0.20-MariaDB-cll-lve
Modx: 1.1.1 latest dev
Chrome: latest version

Here also the PNG->JPG black background issue.
The problem I have here is when I upload even 1 image, it is duplicated with the addition of (1) automatically:
![dupe](https://cloud.githubusercontent.com/assets/1488614/16578284/f5c1a976-4299-11e6-8a0b-dd5fe25759b3.png)

**Comment by janniconl** [comment]
Anyone found a solution for this? 

Especially the black background issue is really nasty and raises a lot of questions at my clients :(

**Comment by bossloper** [comment]
Working fine for me on MODX 1.1.1-beta3. Chrome and Edge browser. PNG backgrounds are fine and no duplicates.

Only thing I can think of is, is it something to do with the PHP GD library setup on some systems (particularly the PNG issue)?

**Comment by fourroses666** [comment]
On some hosts I have these multiple images tooo. :(

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/28
