### ISSUE TITLE
new button in tree :)

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#669]
http://s019.radikal.ru/i601/1607/d8/bdb5d5bb4a16.png

there is a very handy thing, which is missing in the official assembly :)
button which causes the elements of control, a simple popup in a separate window.

- It is very convenient if you need to edit chunks, tv and snippets
- A minimum code
- Button is always in a conspicuous place and do not need to poke through the menu
- Button for a long time to assemble Dmitry

that will tell the community?

tree.php ~ 415-420 line

`<td><a href="#" title="Управление элементами" onclick="window.open('index.php?a=76','gener','width=800,height=600,top='+((screen.height-600)/2)+',left='+((screen.width-800)/2)+',toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no')"><img src="media/style/MODxRE/images/icons/comment.gif" style="margin:3px 0 0 5px"></a></td>`

**Comment by Deesen** [comment]
:+1:

**Comment by pmfx** [comment]
It is very useful. I'm using variation of http://modx.com/extras/package/treegallerybutton 
http://prntscr.com/bqbby7
http://prntscr.com/bqbcaf
Three separate plugins.

**Comment by Fr3ddy7** [comment]
3 plug-in - somehow too much :) If you can once inserted into the tree and forget the code, there is already one button and + button will change nothing and will only improve usability

**Comment by Fr3ddy7** [comment]
its so cool! thank you very much! This greatly simplify the upgrade process, no file editing and adding this button.

**Comment by Deesen** [comment]
Try holding "Shift" while clicking on "Element Management"-Button in Mainmenu. It also opens a new Window in Firefox and Chrome -> https://github.com/modxcms/evolution/pull/670#issuecomment-231705740

**Comment by janniconl** [comment]
I am using the treegallerybutton and the treelementsbutton plugins for quite sometime now. They are great, except for the fact that they are written in a messy way and sadly it does not honour user-permissions. I am working on fixing these issues, planning to do this soon.

@Fr3ddy7 In my opinion 3 plugins is not too much. Besides you only added one button/feature now. You dont want every feature for every user/client (some of them only use the gallery, some all 3 options). The image uploader quicklink for example can be very handy aswell (a copy url button in the image uploader would be nice though :) ).

Did you think of compatibility with the FLAT theme by @Nicola1971? https://github.com/Nicola1971/MODxFLAT-Theme

Might want to make an issue there for this new button (so Nicola1971 can add a font-awesome icon in the FLAT theme)

Thanks for the work!

**Comment by Nicola1971** [comment]
@janniconl 
check development 3.0 branch with sort icon (evo 1.11), elements and gallery button 
https://github.com/Nicola1971/MODxFLAT-Theme/tree/3.0

![flat-3-beta](https://cloud.githubusercontent.com/assets/7342798/16763087/9c84906a-4827-11e6-9d68-7e6b306af4dd.png)

purpose of FLAT 3.0 is to remove all image icons and replace them with font awesome

I currently suspended development because I am completing the new version of the **dashboard plugin** 
https://youtu.be/pAPXm0dJY_g?t=18

**About "user-permissions".**

user-permission to access evo elements are divided by type:
![roles](https://cloud.githubusercontent.com/assets/7342798/16763101/aa0084f6-4827-11e6-8c4c-f6a3157bdaf3.png)
is a bit complicated to apply like other tree buttons. ie:

```<?php if ($modx->hasPermission('edit_snippet')) { ?> ```

**Comment by fourroses666** [comment]
Checked the video. Very nice.

Wish we where able to move resource custom fields and existing fields like that too. :)

**Comment by fourroses666** [comment]
_Also makes me think of an option to change manager language with just a click. (change your current user language) Somewhere a language dropdown button._

**Comment by Fr3ddy7** [comment]
probably the one I do not understand why this the Dashboard, in fact the information in it - this information twice in the system. Work on the site = work tree. And the development of the templates, tv, chunks, stippetah, plugins.

Also it is "cool" I can not say more)

**Comment by Fr3ddy7** [comment]
2 Deesen:
everything works perfectly, like a button, and with the shift button

**Comment by janniconl** [comment]
> Also makes me think of an option to change manager language with just a click. (change your current user language) Somewhere a language dropdown button.

Dont go adding features just because you can, please. It bloats the interface. Why whould a non-dev user want a language switch? I have more than 50 evo users and no-one is ever switching languages, except maybe for the first time. If you want it because you need it a lot while devving, make a plugin and add it for yourself. No need to add it for everyone downloading Modx Evo. Just my opinion though.
