### ISSUE TITLE
Enhancement: Custom folders for "Image" and "File" Template Variables

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#770]
Question and idea for a new feature. 
Would it be possible for "Image" and "File" Template Variable to have/use its own/private folders inside "assets" folder? I see it like this:
1. When creating new Image or File TV, a new option (checkbox) is visible called "Use private folder for uploaded files".
2. When this option is selected two new options appear. First _"Auto folder name"_ (checkbox). Second _"Enter path maually"_ (text input). _"Auto folder name"_ would create folders like "**assets/images_tv/tv_22**" or  "**assets/files_tv/tv_22**" where 22 would be TV ID.

Visuals ;)

![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/18946337/b7b3578c-862e-11e6-8411-f8ff405c22ae.png)

I think it would be very useful in many scenarios.
What do you think?

**Comment by bossloper** [comment]
Should it also have a resource id level for the folder structure?
e.g. assets/images_tv/123/tv_22

where 123 is the resourceid

**Comment by pmfx** [comment]
Not sure. Maybe as another option when creating TV?

**Comment by pmfx** [comment]
Still wondering if "images_tv" folder should be in /assets/ or inside /assets/images/ . 
Maybe it would be better in /assets/images/ then it would accessible by global KCFinder.

**Comment by bossloper** [comment]
Don't think I would put it in /assets/images . it means anyone could delete any image accidentally or otherwise.

I still use Maxigallery quite a bit. It is easy to specify an individual folder for each resource. This helps keep my customers organised! Otherwise they just end up with hundreds of images in a big mess in the top level of the images folder. Having them by resource keeps them separate so you can see exactly what appies to that page and with the addition of a plugin it can delete the resource image folder if the resource is deleted and purged which keeps things tidy and recovers disk space.

**Comment by pmfx** [comment]
That make sense. So "assets/images_tv" then. And an option to include resource id in the path.

![screenshot_4](https://cloud.githubusercontent.com/assets/10888055/18947974/81877e34-8635-11e6-9354-54c8efba0521.png)

**BTW I think "File Template Variable" could have the same feature!**

**Comment by bossloper** [comment]
Looks good. If you were able to use [*id*] in the manual folder path then that would be the ultimate.

**Comment by pmfx** [comment]
Here you are ;)

![screenshot_5](https://cloud.githubusercontent.com/assets/10888055/18948429/4c9d80f4-8637-11e6-9e91-4f586b323182.png)

Now we need a volunteer...

**Comment by nick0** [comment]
This is a really nice idea.

I personally prefer the term "Unique folder" over "Private folder" because to me Private folder sounds like its protected and for their eyes only. Unique folder means distinct and separate and perhaps is a better label for this.

I like the idea of automatic inclusion into assets/images/images_tv (and likewise assets/files/files_tv) just to keep things neater. Just my personal preference. Could this path choice be provided as an option?

Excellent work @pmfx

**Comment by pmfx** [comment]
@nick0 Thanks. I think "Use private folder" term works better than "Use unique folder". "Use unique folder" refers more to "Name folder automatically" option. If you think "Use private folder" is too strong, then maybe "Use separate folder" or "Use new folder" term will do the job?

**Comment by bossloper** [comment]
How about "Use alternative folder"?

**Comment by pmfx** [comment]
@bossloper Boom! That sounds perfect.

**Comment by Nicola1971** [comment]
+1 but don't like names

From my marketing view

Private folder: seems protected folders
Unique folder: non very clear or me 
Alternative folder: like custom folder,  should be an alternative to assets/images , not a sub folder.

Suggest:
Dedicated folder
Related folder
Resource folder
Archive folder
(just) Album :)

**Comment by Nicola1971** [comment]
Album sounds good to me

**Comment by pmfx** [comment]
Or just "**Custom folder**" you mentioned. Easy to understand.

**Comment by Nicola1971** [comment]
Custom, like alternative: is something different - not assets/images

Better "dedicated" : dedicated to a resource (id), to a gallery, a slider, a catalog collection...

**Comment by Nicola1971** [comment]
Ok I'd not understand, it's really an alternative folder (checked better screenshots)

Go for alternative or custom.

**Comment by nick0** [comment]
Good thoughts here. Point taken on Unique. Agreed.
I like any of these...
New folder (for the simlicity)
Custom
Dedicated
All makes sense to me.
Nice one.
