### ISSUE TITLE
what version is correct for this release 1.1.1 or 1.2 ? 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#828]
I think better is 1.2 
We made a lot of changes both functional and appearance.

**Comment by pmfx** [comment]
I think this release deserves 1.2 :)

**Comment by Deesen** [comment]
IMO v1.2 should contain also manager theme-engine, everything before theme-engine I think 1.1.1 fits better.

**Comment by Nicola1971** [comment]
for me 1.2

for my marketing view, release numbers are very important to awaken the public's attention
1.1.1 seems too much a bug fix release of 1.1, in this release there are many new features

I think most of new additions of this release will be improved in next days and months, so there will be a 1.2.1...

@Deesen don't know how much time the new theme engine requires to be completed but, for me, is an even bigger and important update and deserves a resounding release number (1.0.5 or 2.0?)

**Comment by Deesen** [comment]
Ok then 1.2 makes also sense to me. And I also don´t know what the bosses think of my concept or if they are having their own ;-). I was just thinking loud because implementing a theme-engine is definetly a milestone so to iterate to next version like 1.2 or 1.3, because several plugins/addons could not be compatible if changes are too big in the end.

"Modx 2.0" for me is Revo. The confusion is just too big IMO, staying within "v1.x.x" will avoid it.

**Comment by dmi3yy** [comment]
Then will be 1.2 ) 
need write  new ChangeLog  and public  1.2-rc1 on modx.com  for mass testing

**Comment by Nicola1971** [comment]
you're right, I had not thought about revo.

we will have to make hundreds of minor versions :D

**Comment by dmi3yy** [comment]
About  themes by Default i think  need only  MODxRE2 another move to extras. 
http://take.ms/zQN74

**Comment by Deesen** [comment]
evolution-1.1.zip 5.570kb
evolution-develop.zip 8.302kb

What exactly happened? :-D

**Comment by pmfx** [comment]
I don't see why we cannot have Evolution version numbers above 1. Evo and Revo are separate branches/products therefore there is no issue/conflict when we will have Evolution 2.0 or Evolution 3.2.2 as long as we call it "MODX Evolution".

**Comment by pmfx** [comment]
@Deesen done some cleaning up in #832 and we are down to ~7.200kb ;)

**Comment by fourroses666** [comment]
Question, do we want to remove some default snippets / plugins in the future?
Making use of the Extra's to download plugins/snippets like jot?
Start clean kinda like Rev.

**Comment by pmfx** [comment]
@fourroses666 not sure about removing default snippets/plugins. There are some that I often delete in my projects - like Jot - but I prefer to delete those 2 or 5, rather than install 10 from Extras. 

Actually, thats one of things that **people are complaining** about in Revolution - that they have to install all snippets and plugins like Wayfinder in every new project. Thats a lot of clicking and time. Start clean is not always a good solution.

**Comment by dmi3yy** [comment]
In my custom i delete some snippet 
Like: 
- ajaxsearch 
- weblogin
- jot 
Its no need at 90% project 

Отправлено с iPhone

**Comment by fourroses666** [comment]
I agree, maybe even more removed.

I have no problem having to install stuff from a clean system. Where there really complains?

**Comment by modxuser** [comment]
My thoughts on the things being discussed here.

**Manger Themes:**

I would also opt to dumping all manager themes except the latest that has recently been built. Not that it pleases me, but simply because the others haven't been updated to accomodate the new stuff (so far as I have understood).

**Versioning:**

Versioning shouldn't in my opinion take notice of Revo - Revo and Evo are standalone products and have nothing to do with each other. They both only have the MODX LLC in common and the interest of the LLC towards Evo is "0".

**Snippets:**

My default snippets I have in every site I build are the following:

- ditto
- eform
- if
- ultimateparent
- wayfinder

If I need others they are installed later, unless it's a clean install where they are installed then

I will be looking into "Doclister" when I install the latest release, as a substitute for Ditto, that is, if it can do everything Ditto can.

looking at the current "develop" I see new snippets, what are:

- DLUsers
- summary

Going for a 100% clean install isn't what I think is the best approach, this is Evo not Revo - just because things are done in Revo, they don't need to be done the same in Evo.

A Side note:
Has PHX bee removed from the default install, as I can't find it in the code anywhere. This could be a problem as many Evo users still use it (I don't)

**Comment by modxuser** [comment]
If you guys are cleaning code out, what about:

assets/js/jquery.min.js
assets/js/jquery/jquery.min.js

Both are the same version - 3.1.1

Also, why are major changes not be presented to the MODX Forum community, why are only a handfull of people in GitHub voting on changes that affect thousands of Evo users ?

**Comment by pmfx** [comment]
@modxuser I have similar default snippets set + phpthumb, firstchildredirect, 

DLUsers - not 100% but it for DocLister. Maybe extender.
Summary - truncating content.
I don't know, maybe those two will be dropped in final release as they are not even in install. @dmi3yy ?

Not sure why PHx was removed. Maybe because of new built-in filters/modifiers. Actually I'm using PHx a lot :)

**Comment by dmi3yy** [comment]
DLUSERS and Summary  get from Doclister, i think need more clean do this.
https://github.com/AgelxNash/DocLister

Doclister need for:  
https://github.com/Pathologic/SimpleGallery
https://github.com/Pathologic/SimpleTube
https://github.com/Pathologic/SimpleFiles
https://github.com/Pathologic/FormLister
https://github.com/Pathologic/FastImageTV
https://github.com/Pathologic/DLRequest
https://github.com/webber12/evoSearch
https://github.com/webber12/eFilter
https://github.com/Pathologic/Selector

and more great solution.    

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 17 октября 2016 г. в 13:01, Piotr Matysiak написал:

**Comment by dmi3yy** [comment]
PHx no need now. new built-in filters/modifiers.

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 17 октября 2016 г. в 13:05, Lukianenko Dmytro написал:

**Comment by pmfx** [comment]
@dmi3yy built-in filters/modifiers - where is documentation for it?
Does it use the same syntax as PHx? Will users have to change something in their code?

**Comment by dmi3yy** [comment]
Info in help http://take.ms/M87d3
https://github.com/modxcms/evolution/issues/623


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 17 октября 2016 г. в 13:17, Piotr Matysiak написал:

**Comment by pmfx** [comment]
Thanks @dmi3yy I didn't look there before. Thats cool!

And this is super-cool too! :

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19434631/df60f9a6-9466-11e6-972a-87d2cdc84579.png)

**Comment by dmi3yy** [comment]
small fix for more space:) 
http://take.ms/HHP0l
http://take.ms/NIqNq

**Comment by nick0** [comment]
I still use PHx - happy to replace with the new filter / modifiers if it works as well as PHx and if there is documentation somewhere.

From the default snippets currently distrbuted in Evo, I use

- Ditto 
- phpthumb
- eForm
- FirstChildRedirect 
- if
- UltimateParent
- Wayfinder
- AjaxSearch

Please don't remove these unless there are replacements with documentation and they work as well.

> but I prefer to delete those 2 or 5, rather than install 10 from Extras.

I agree 100% with this.

**Comment by Deesen** [comment]
I am asking myself, how about custom modifiers like in PHx? Are they possible with new filters/modifiers? If yes, how exactly?

**Comment by bossloper** [comment]
not sure, but can this be closed... pending @nick0 ok?

**Comment by dmi3yy** [comment]
Сlose

Отправлено с iPhone

**Comment by nick0** [comment]
yes, thanks @bossloper

**Comment by bossloper** [comment]
@dmi3yy - this is yours to close :-)

**Comment by fourroses666** [comment]
AjaxSearch is the largest snippet. About 1MB. 
I often use that. When removing it from the webserver and upgrading Evo it comes back. 
Don't know whats the smartest thing to do. If you ask me I rather have it installed when I need it with the Extras. And when there is an update the Admin gets a notice or on the dashboard.

Jot I never use. But if you choose Demo site on install you need the files. Hmmm.
