### ISSUE TITLE
New MODX.com website and Evolution

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#866]
https://modx.com/

I took me some time to find Evo page
https://modx.com/community/modx-evolution

**Comment by Nicola1971** [comment]
For me, a bad presentation of Evo.

**Comment by pmfx** [comment]
Indeed. This is what I said on MODX Slack channel: 

> new website is nice and modern looking, but sad to see that Evolution has been pushed far far way. "Community" is the last place I would be looking for it. And it was even removed from default Downloads section. Bummer. I use both Evo and Revo but this new site is like a parent having two kids and showing which one is loved more... 

But hey, we can't do much about it, right? What we can do is to make Evolution better and better and 1.2 is going to be an amazing release and feature-rich upgrade for all Evo users. And thats more than cool for me.

**Comment by Breezer** [comment]
No doubt this has been in the works for a while, every time someone requests evolution help on the forum one of the revo cheerleaders chimes in with "shouldn't you upgrade to revo"...

Evo lives in the basement under the stairs now lol

**Comment by pmfx** [comment]
Yeah. And this photo of old Kodak camera. Jeez... 

![2016-10-28-00-56-58](https://cloud.githubusercontent.com/assets/10888055/19788604/a0c4a530-9ca9-11e6-8e9e-7644ba3f20e6.png)

Anyway. I've always liked Kodak :D

**Comment by Nicola1971** [comment]
This image Is very sad and denigrating

**Comment by modxuser** [comment]
The new site has been worked on for a while - being a forum moderator you have access to all channels, including those that are not public and as such I was able to view the discussion.

My opinion of the new site - it sucks. That they are now promoting Revo as the "all singing all dancing" piece of tech that it isn't amazes me, look in the forum and the truth can be found - tons of problems that have been there from day one.

Why the site sucks, simply because it has demoted Evo to the bin, there are still thousands out there using Evo, whether they know it or not is a different matter, but when it comes time to update, try and find your way around the new site to find a download - not easy as @Nicola1971 has already mentioned. This is [the download page](https://modx.com/download), no mention at all of Evo.

The LLC say a lot when the day is long, they said a couple of years ago that Evo + Revo were being dumped for MODX3 - what happend there = nothing

In my opinion the introduction of MODX CLOUD basically crippled MODX, why, simple, the LLC concentrated on the cloud instead of cleaning up what was already there - Revo still has problems that have been around for years. Look at the CMS rankings around the net, look at what's being discussed, you will hardly see MODX in those stats nowadays.

The LLC haven't looked at Evo for years and don't know what has been going on with it - the community developers have done a **fantastic job** of keeping Evo alive and with the latest modifications have put it back inline with the latest versions of PHP, making it a worthy contender to go ahead with in the future.

I have tried Revo and find only one or two things that benefit me in a way that Evo can't, but I am talking from the benefit of third party plugins, not the Core. I run large sites with Evo and don't have any server problems at all and I expect that in the future, the development of Evo will make it even more competitive.

Imagine, Evo with a fully responsive back-end. This doesn't seem to far away now that the back-end is being cleaned up by a lot of proficient community developers (back + front-end).

If my post has offended anyone, sorry, but the truth hurts.

**Comment by modxuser** [comment]
Can someone please update the [README.md](https://github.com/modxcms/evolution/blob/develop/README.md) with the following:

**Evo:**
https://modx.com/community/modx-evolution

**Download:**
https://modx.com/download/evolution/

**Previous Releases:**
https://modx.com/download/evolution/previous-releases.html

**Extras:**
https://modx.com/extras/?product=evolution

**Documentation:**
https://docs.modx.com/evolution/1.0

**Comment by dmi3yy** [comment]
I wrote to Ryan that he has read this thread.
I'm just not happy that our work pushed into the interior.
But from the point of view of the development and monetization I understand their actions. Since Evo hinders and creates competition REVO and no one needs.

**Comment by dmi3yy** [comment]
We ourselves can make a good site for EVO
i have for start: 
http://evolution-cms.com
http://extras.evolution-cms.com
http://cheats.evolution-cms.com
http://docs.evolution-cms.com

Do in one design. 
Do multilang. 

I do not see any reason why we can not do it :)

If you do together that it takes not so much time and energy)

**Comment by nick0** [comment]
"shouldn't you upgrade to revo"...
ha, that's always a good one to hear inst it @Breezer. I always find that type of comment funny because as far as I know an actual smooth upgrade from evo to revo was never actually developed as promised.
As soon as I saw the ManagerManager replacement in the first 5 minutes of trying Revo with forms / complications etc, they lost me.
I forgot about the talked up Modx3 which was going to solve all the problems. That obviously died in the pants.

Well said @modxuser, that was interesting.
And I ditto (Evo pun intended) what you said about the great community developers here, there are some very clever people steering Evo in an exciting direction and doing an excellent job with not a lot of kudos. Well done to you all.

At some point perhaps this Evo should no longer be considered Modx and should become a new brand given Modx dont seem to have anything to do with it anymore.

**Comment by dmi3yy** [comment]
I am very grateful to the MODX Team for the EVO branch. 

Therefore, before making a fork. I talk to them and learn theirs plans. The last 4 years we have made changes and do everything that used to brand MODX was better as well as for me MODX stronger with 2 branches. than one.

And divide and run separately is only in extreme cases

**Comment by dmi3yy** [comment]
I love the Kodak but comparing it with its not nice to me.
- The Evo is not xPDO but there is MySqli - which is faster
- Yes we not work on MODX CLOUD but work  on all chipest hostings.
- Yes we havent ExtJS in core but in REVO extJS3  now ExtJS 6 !!! , in Evo jQuery 3.1. 
- Yes not all code is OOP but, he work faster! 
- Evo the best for small and midle site where no need subversion. But REVO too cant work with subversion. 
- Evo work with 100 000+ docs, and on php 7.  Like REVO no problems ) 
- Have great assets and repository. 
- Revo have big trouble with speed on manager and i always see white screen. its from firs relises and now 2.5+ and still the same problems

and more more more........

**Comment by Nicola1971** [comment]
It's not just the Kodak (that i love too), it's more about words. 
All words sounds so demotivating for Evo

Remember me Dante Alighieri's (italian poet) words "_Abandon all hope, you who enter here.._" (written on the hell door) :D :D

I understand that Revo team must push their primary project, but

> In the beginning, there was MODX Evolution…

No, In the beginning, there was MODX 0.9.x, not Evo

....and _**there was MODX Evolution**_, sounds like you are talking about something dead

> MODX Revolution—a modern, more secure, and more flexible reinterpretation of Evo. And like its predecessor, MODX Revolution is ready for whatever comes next.

Ok, Revo is a really cool CMS, i understand, but why you are still talking about Revo for half text of Evo description, when you talk about and promote Revo in all rest of the site?

I agree with @dmi3yy : MODX is stronger with 2 branches, I saw a lot of inspiration between the two branches, but seems that modx team did not feel this way

**Comment by pmfx** [comment]
@Nicola1971 I had exactly the same impression/feeling when reading that page. Very disappointing. It is not a description of Evo as a solid, stable and powerful CMS but something that you say on funerals. Give me a break. They should change it.

**Comment by modxuser** [comment]
**"In the beginning, there was MODX Evolution"**
Nope, there was etomite then 0.9.x.

**"Fewer Security Reports than WordPress"**
Only because MODX doesn't have the same reach as WordPress, WordPress takes so far as I know approx. 18% of the CMS market, whereby MODX isn't listed

**"The world’s fastest, most customizable Open Source PHP CMS."**
They obviously know something I don't, my experience has shown that this is not true, customisable - yes, fastest - no.

**"a modern, more secure, and more flexible reinterpretation of Evo"**
Why do they think Revo is more secure than Evo ? It's open source code, if a mistake is made someone will find it and exploit it, doesn't matter whether it's Revo or Evo. More flexible, possibly, but (IMHO) only due to third party code.

**"we still have a soft spot for MODX Evolution"**
That's why they have hidden it in the main website


In my opinion breaking away from MODX LLC shouldn't harm Evo at all, why, because they don't do anything with it anyway. **You guys here do all the work, the LLC don't.**

I think it would be a good idea for the future to create a standalone site for Evo, ask for permission to move the documentation over, move the extras over and start from scratch.

Although, I must say - the extras do need to be looked at and a lot need to be dropped, an extensive amount are outdated and a lot of them are no-longer supported by their original developers.

It might also be worth looking into code that lingers on other sites, the Russian community have a huge amount of code and if I remember rightly @Breezer built an Evo bespoke forum add-on / plugin.


At the time of writing this post, Evo 1.1 had been downloaded 13,971 times. If this figure is correct, what is the real figure of sites using it.

I for one updated 56 sites together with a friend, but only downloaded the software once. So saying that Evo is an outdated CMS, is in my opinion very naive, especially since the code has been updated on a major basis over the last 3 / 4 years.

Very tedious to update so many sites, but that's one of the main drawbacks with all of the MODX systems, that's where WordPress has the upper hand with its built in update mechanism.

Possibly something to think about for the future ?

**Comment by dmi3yy** [comment]
I have small statistic where used extras on EVO  

http://take.ms/KsIxN

27956  - different domains which ran extras.  

Extras  start 3 years ago with my custom and  1year in Off Evo  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 28 октября 2016 г. в 14:09, modxuser написал:

**Comment by bossloper** [comment]
If we wrote our own version of https://modx.com/community/modx-evolution do you think they would update the text?

@modxuser I doubt we would be able to 'break away' and keep the MODX name. And that name still has some value.

**Comment by dmi3yy** [comment]
Yes 

Отправлено с iPhone

**Comment by Nicola1971** [comment]
something is changed in Evo page.
removed " more secure, and more flexible" from Revo description

now is just
> MODX Revolution—a modern reinterpretation of Evo

**Comment by pmfx** [comment]
Yeah, it is better. I posted my thoughts on https://modxcommunity.slack.com/messages/general/ today. Maybe they got more messages from others about how Evo is described. I've asked to remove/change picture of Kodak camera too.

**Comment by Nicola1971** [comment]
Not much is changed on modx.com page :(

Maybe is the time for a site dedicated to Evolution? 
Forking or not, we need more visibility and a better presentation of Evo features.

I have a "half ready" project that can be easly finished and moved to the new Evo site (evolution-cms.com?):

Two years ago I have started a project for an Italian MODX site, always updated the system, but never found help to finish: translate all documentation was too much for me and i don't know much about revo to write for both branches.

**Comment by fourroses666** [comment]
I do like a seperate website with all documentation, extra's and could be multilang. 
We really need to think about this. Would it be smart, the future, the work that needs to be done, pros and cons.

**Comment by pmfx** [comment]
I can contribute to this (in both design and front-end) if we decide to do it.

**Comment by Nicola1971** [comment]
If we work together, we can get it in really short time.
I think we (me, @fourroses666 , @pmfx, @Deesen ) have found a good feeling working together on the new manager theme and the new front end template.

Actually, the template is just a basic bootstrap template, based on a powered version of my Start template. So, a knowed CSS framework to work and modify together.
I worked most on features like extras section,  multitv for download, videos, galleries and various features. We have all tools, , Just need a custom style.
There is an extra section based on efilter snippet, a download section and other things.

I will move the project to a dev server to check and work together.

Of course, I'm waiting opinions about it from our boss @dmi3yy and @yama, but with a scratch of the project we can do a kind of "pull request" :-D

**Comment by dmi3yy** [comment]
I think  do evolution-cms.com  great idea.
It does not matter whether the brand MODX project or not.
but gather the actual site is on EVO and maintain it will be a very useful thing

**Comment by yama** [comment]
My opinion is about the same with Dmytro
MODX was born in form to succeed Etomite.
The origin of the name of MODX is "the thing which collected convenient MOD".
To tell the true intention, I do not like this name.
I do not like CMS such as the assortment...

I think the evolution to be a result of the natural selection. It is not that a beautiful wing grows suddenly.
A necessary thing survives. We need evolution.

**Comment by mgzawlinoo** [comment]
I am not a web developer . I'm still use modx evo for all of my websites (more than 50 currently run, all are smooth and working well).
Thank you guys for still maintain and developed modx evo .

**Comment by Nicola1971** [comment]
Ok, I think should be nice get evolution-cms.com ready for 1.2, so i moved my project from modx.it to evolution-cms.it. 
Just to have a **draft**, to discuss together and start developing together

Remeber it's just a draft:
http://www.evolution-cms.it/

**Comment by dmi3yy** [comment]
http://developee.evolution-cms.com  - new style for extras. but don’t finished (  


good druft but need more designed.  and styled.






--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 7 ноября 2016 г. в 20:27, Nicola написал:

**Comment by pmfx** [comment]
I think there are two options for a new site:

1. Buy a great ready to use HTML template (or find a nice free option) and modify what's needed. 
2. Create design from scratch and code it. 

I think for now option 1 is a fast, simple and optimal solution. And we don't need to have whole site content ready like now. Just home page (don't have to be content-heavy), about, features, download and that's it. For start.

100% custom design would take a lot of time and effort to get good results. Maybe later we could work on it. But I don't think any of us have so much spare time right now.

Either way it is not "Evolution issues" related so I think we should move this discussion to a private place like Slack or [Glip](https://glip.com) to talk about details.. What do you think?

**Comment by dmi3yy** [comment]
I asked the designer to draw something interesting. Hope to do soon)

We need own style. what would a little escape from REVO.

And then we can do on the templates or framework, but to improve it under our style.

Make 1 more site that will be similar to modx.com (like as template from themeforest) wants.

 on the site(modx.com) is written about EVO «classic codebase»

and I really want to save it, and further, in the design of the site, including.   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 8 ноября 2016 г. в 00:02, Piotr Matysiak написал:

**Comment by nick0** [comment]
Call me crazy... Evolution users often refer to it in the shorthand Evo - perhaps the standalone could be called Evo CMS, with website address evocms.com or similar?

**Comment by dmi3yy** [comment]
about name and what now can found:  

http://evo-cms.soft112.com
http://blog.evolution-network.ca
http://www.evo-german.com
https://www.facebook.com/EVOCMS

But we are too on top )
http://take.ms/I1Fho
http://take.ms/dAoVk

i think full name Evolution  
short name Evo

we can get 2 domain )  
evolution-cms.com
and
evocms.com

I think this is a not problem))  



--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 8 ноября 2016 г. в 01:58, nick0 написал:

**Comment by dmi3yy** [comment]
but for about name no one live project  with name Evo Evolution  and its good for US  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 8 ноября 2016 г. в 02:15, Lukianenko Dmytro написал:

**Comment by dmi3yy** [comment]
https://evocms.slack.com

**Comment by Nicola1971** [comment]
> good druft but need more designed.  and styled.

yes, as i said, just a draft :)

I think there are a lot things to talk about the new site, not just about design

> Either way it is not "Evolution issues" related so I think we should move this discussion to a private place like Slack or Glip to talk about details.. What do you think?

agree

**Comment by dmi3yy** [comment]
tomorrow we do slack account ) for this )

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 8 ноября 2016 г. в 16:07, Nicola написал:

**Comment by Nicola1971** [comment]
Ops, just done evolution-cms.slack.com

**Comment by Ronef** [comment]
Ooops, https://evocmf.slack.com is done too.

**Comment by dmi3yy** [comment]
i think better  https://evocmf.slack.com
similar with  evocmf.com )  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 8 ноября 2016 г. в 16:58, Ilyas написал:

**Comment by fourroses666** [comment]
Hmm, CMF is the right naming but CMS is much more known by all.

> Evolution is the framework with which you build your own CMS, to your specifications, to suit your needs. 

But do you really want to name it like that?

**Comment by Nicola1971** [comment]
Agree with @fourroses666, better CMS

**Comment by esszett** [comment]
Just to say THANK YOU for all your great work on evo – today I stumbled upon this: the W3C is giving it's consent for evo… :o)
https://www.w3.org/TR/html-design-principles/#evolution-not-revolution

**Comment by dmi3yy** [comment]
Into text on new site ready %)

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 8 ноября 2016 г. в 17:53, esszett написал:

**Comment by pmfx** [comment]
@esszett Haha, this is a good one!

**Comment by nick0** [comment]
Agree with @fourroses666 and @Nicola1971 - cms will make more sense to many people (myself included). I think more people would search for "cms" over "cmf" when look for a website content system
Plus cmf looks like a typo.

Haha, that is gold @esszett

**Comment by Ronef** [comment]
I believe it is not so important CMS or CMF) But the domain `evolution-cms.com` is not the best, because it is too long and contains a hyphen. `evocmf.com` is more simple, clear and memorized. Unfortunately, `evocms.com` is [already busy](https://who.is/whois/evocms.com)(

**Comment by fourroses666** [comment]
I really would like to see CMS, even thow like I said CMF (framework) would be correct name I rather see CMS like Drupal and Modx Revolution is calling it and probably many more) It doesn't feel right to me.

Its not that CMS isn't correct to name it. Longer URL doesn't matter to me. We already have `evolution-cms.com`.

**Comment by pmfx** [comment]
Maybe getevo.net or getevocms.com? Both available.

**Comment by Fr3ddy7** [comment]
evocmf.com (:

**Comment by Ronef** [comment]
If we can't decide “CMF” or “CMS”, we must avoid it in domain name. IMHO, `.com` is required.

**Comment by fourroses666** [comment]
Thats ok with me. Just don't like to see cmf in the URL. On the site itself its ok I guess to call framework (to build a cms).

evo.site and evolution.site are not available.

Any more ideas?

**Comment by bossloper** [comment]
evo.ninja lol :-)

**Comment by nick0** [comment]
> But the domain evolution-cms.com is not the best, because it is too long and contains a hyphen.

I don't think the length of this one is too bad but I agree 100% on the hyphen. For some reason it looks less professional to me with a hyphen in it. Something about hyphens in domain names don't look right to me.

> Maybe getevo.net or getevocms.com? Both available.

Something along these lines with "get" or "go" or "use" or "do" etc at the start could be a nice creative way to get an appropriate domain.

**Comment by nick0** [comment]
I see the .website domain is coming... evo.website?

**Comment by Nicola1971** [comment]
Evo Cms exist, it's a php nuke fork. So we need an "Evolution" domain

**Comment by nick0** [comment]
Ah, good checlking @Nicola1971.
Inline with @pmfx, what about getevolution.com or theevolution.com?

**Comment by fourroses666** [comment]
I like getevolution.com

**Comment by Nicola1971** [comment]
waiting for the domain name, can we choose a slack account to move this (not issue) discussion? 
at least a temporary slack account, before the official domain name.

@dmi3yy do you have done something about it?

**Comment by Ronef** [comment]
Go to [evocmf.slack.com](https://evocmf.slack.com/), send email adresses to me or @dmi3yy.

**Comment by dmi3yy** [comment]
I think   
Evolution-cms 
Getevolution 
Evolutioncms 

Almost the same and its not critical for me 


Отправлено с iPhone

**Comment by Nicola1971** [comment]
@Ronef, don't have your mail, you can find my email in github profile

**Comment by Ronef** [comment]
@Nicola1971 invation has been sent. And my email now is displayed in profile, thanks!

**Comment by Ronef** [comment]
https://evocmf.slack.com/messages/domain-name/

**Comment by fourroses666** [comment]
maybe you can add me tooo

**Comment by pmfx** [comment]
and me please

**Comment by nick0** [comment]
And me also please. Email sent to Ronef. Thanks all

**Comment by fourroses666** [comment]
My email is on me profile page!

**Comment by Breezer** [comment]
I would like to be added too please.
drewfras@gmail.com
