### ISSUE TITLE
incorrect work  new element locked function

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#945]
http://take.ms/54z9G

We have one of the functional users online http://take.ms/y0pdW
and if I edit the document online, and I then everything is OK and does not unlock until I online.

As soon as I am not online then remove my lock. For the current implementation is not very correct and beautiful

**Comment by Deesen** [comment]
Sry pls explain what should be more correct and beautiful? I will work on it.

**Comment by dmi3yy** [comment]
We need to put a check on the line if the current user.
If I open page online but I do not remove the lock.
If I do not have to remove the active users. so I think even less code will be so beautiful


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 21 ноября 2016 г. в 11:41, Deesen написал:

**Comment by Deesen** [comment]
We discussed how to improve the lock-mechanismn and get it free of trouble as follows:

- revert everything related to "lock - interval" and no more relying on periodical server-requests (too many factors that can lead to unnessecary issues)
- add a new simple table "active_user_sessions" with fields `userid`, `lasthit`
- `manager/index.php` and `includes/session_keepalive.php` will update this table at each request when session is valid / user is logged-in
- rename "lock cleanup delay" to "keep session alive interval" and use this value in `session.js` / `keepMeAlive()`. If `lasthit` exceeds this interval, MODX will assume this user is no more online / logged out
- locked elements will only be unlocked
  - when user hits logout-button (ALL locks related to this user will be deleted)
  - by `manager/index.php` at every request, when no corresponding valid session in `active_user_sessions` exists (exceeding "keep session alive interval")
  - window.beforeunload triggering AJAX unlock-request when needed (hopefully free of trouble):
    - unlock for save+leave, cancel-button etc
    - no unlock for save+stay
    - no unlock when clicking "edit" on the same element multiple times in a row
- localStorage to share required parameters between windows like last clicked element/id
  
This way bad connection or whatever may go wrong, will not lead to unexpected behaviour or error-messages. While we still can have multiple locks, and avoid those everlasting lock-"corpses" (and customer phonecalls), just because a user (or admin) closed his browser and forgot to logout or press cancel.

**Comment by bossloper** [comment]
Sounds like a plan!
Would these changes potentially break any third-party snippets/plugins/modules (though I don't know of any) and so prevent some from upgrading to 1.2 and beyond?

Along those lines, please also check to make sure Quick Manager+ lock/unlock (for resources edit, inline tv edits etc) works after these improvements are implemented.

**Comment by Deesen** [comment]
No it cannot break anything I know of. The original "active_users"-table is still working like before, no changes.

Reg. Quickmanager etc you are right but as I know DivanDesign wants to release v0.7 with MODX 1.2 so maybe they take that into account. Will ask. And every component user this "active_users"-table to check locks needs to be modified to take all locks into account.

**Comment by pmfx** [comment]
I wonder if "lock" icon is right. Can be misunderstood as a "private resource". Maybe Exclamation icon would be better?

http://fontawesome.io/icon/exclamation-circle/
http://fontawesome.io/icon/exclamation-triangle/
http://fontawesome.io/icon/exclamation/

**Comment by mcparana** [comment]
also click on other resource/element in tree has to unlock edited resource/element if any (maybe window.beforeunload triggering AJAX unlock-request will handle that, dont know)

**Comment by Deesen** [comment]
Yes I´m already fighting with all those issues.

**Comment by Deesen** [comment]
One issue is left as already mentioned on Slack: The Unlock-Ajax-Button and "Remove Locks" is still working, I did not removed it yet.

Do we need any "unlock"-buttons? Locks will clean-up automatically now, there is no need for any unlock-function except admins want to have the option to "steal" a lock, to prevent a user editing a resource for any reason. This is the only usage I can imagine.

**Comment by bossloper** [comment]
I guess there is no harm in leaving the 'unlock' (steal!) option there for now? Could be revisited at 1.2.1 and at least it gives a safety net for removing locks if there are any unforeseen issues.

**Comment by bossloper** [comment]
@Deesen - Is the unlock mechanism working correctly (latest dev)? I've been login in via various browsers and devices ;-) in the last couple of days. I'm usually not cancelling the resource edit but just closing the browser so presumably relying on the 'exceeding "keep session alive interval"'. 
My manager is showing resources still locked from 48hours ago which seems a little suspicious.
Anyone else seeing this?

![untitled](https://cloud.githubusercontent.com/assets/1744687/21176660/ab0d6ad0-c1df-11e6-9e57-8f336fa02bbb.png)

**Comment by Deesen** [comment]
Nothing has been changed yet so this seems to be an issue since 1.2. I also noticed it at only one of my customers. But using logout-button helped. It is strange issue, I cannot recreate it intentionally.

**Comment by bossloper** [comment]
OK, this is definitely an issue then, and yes could well be from 1.2.0. Do you want to reopen or add a new issue?

I have multiple entries in that table, all with the same internalKey and various lasthit dates.

I interpreted from this line:
"by manager/index.php at every request, when no corresponding valid session in active_user_sessions exists (exceeding "keep session alive interval")"
... that each entry in active_user_locks would be checked against lasthit dates being outside the session alive interval?

**Comment by bossloper** [comment]
It seems completely reproducible:

1) Edit a resource
2) Close the browser window while still editing the resource
3) Open browser back up - resource still shows locked and will be locked unless edited again and cancelled or a proper manager 'logout' is done.

So as far as I can tell this is still the same situation of stale resource locks as before 1.2.0?
