### ISSUE TITLE
mootols

### ISSUE THREAD

**Issue by Cipa** [modxcms/evolution#954]
Hi, 

Mootools was completly removed from [Clipper](https://github.com/ClipperCMS/ClipperCMS), the same code can be applied to the current modx evolution.
All mootools function were traslated into "jquery" or regular javascript

I don't see any discussions for removing mootools. Any future plans?

Thank you

**Comment by Nicola1971** [comment]
+1 to remove mootools.

**Comment by dmi3yy** [comment]
+1

Отправлено с iPhone

**Comment by yama** [comment]
If possible, I would like to anything other than "jQuery UI".
Somehow, I do not like it ...

**Comment by fourroses666** [comment]
Is it an idea to Assign it to someone (_if someone whould like to do it offcourse_) and add a label to it "like Evo 1.3"?

**Comment by Cipa** [comment]
So what do you prefer to jquery ui?

**Comment by mcparana** [comment]
for my modules i dont use jquery-ui at all.
im using:

- tabs, dropdowns, modals etc - bootstrap js
- summernote (http://summernote.org/) - wysiwyg editor
- chosen (https://harvesthq.github.io/chosen/) - select inputs
- icheck (http://icheck.fronteed.com/) - checkboxes and radios
- bootstrap datepicker (https://bootstrap-datepicker.readthedocs.io/en/latest/) - date inputs
- peity (http://benpickles.github.io/peity/) - charts
- alerts - some wrapper plugin around bootstrap modals instead of js alerts
- self-written javascript for 
![date](https://cloud.githubusercontent.com/assets/11875737/20559512/8ae30084-b17d-11e6-8ea2-d62f6893dde2.png)
![wysiwyg](https://cloud.githubusercontent.com/assets/11875737/20559510/8ae24946-b17d-11e6-9b88-9f8282d6a9a1.png)
![checkboxes](https://cloud.githubusercontent.com/assets/11875737/20559511/8ae2f1a2-b17d-11e6-80f0-d4db40490d63.png)
![selects](https://cloud.githubusercontent.com/assets/11875737/20559513/8ae7e1b2-b17d-11e6-92d2-fce18e4a31e5.png)



ajax filtering and sorting in tables.

**Comment by mcparana** [comment]
there is useable plugin for handling tables with sorting and pagination, **Tablesorter** (http://tablesorter.com/docs/#Download)

i used it for a while.

**Comment by Cipa** [comment]
So boostrap for manager. 
Tablesorter was alredy implemented on Clipper so should be easy enough.

**Comment by mcparana** [comment]
i think using html-css-js framework is a good idea for manager.
its easy to customize and fast to develop solution.

as for me, bootstrap provides useful set of js to implement manager ui

**Comment by Cipa** [comment]
I see easy-ui is already set up inside assets/js

Is the plan to use easy-ui for the manager as well?

**Comment by dmi3yy** [comment]
we are work about this  i think in near future remove all motools 
new way of EVO here. 

https://github.com/evolution-cms/evolution/
