### ISSUE TITLE
Errors while update

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#990]
(last git develop version)

**Simple update**:
```
Warning: explode() expects parameter 2 to be string, array given in \install\setup.info.php on line 174
Warning: Invalid argument supplied for foreach() in \install\setup.info.php on line 175
```
Is [there](https://github.com/modxcms/evolution/blob/develop/install/setup.info.php#L173-L175) error ?

**Advanced update**,
 after check connect to base and settings for DB and click Next, gets popup message 
"enter administrator password", but no input for this

**Comment by Deesen** [comment]
I guess

    $dependencies = explode(',', $dependencies);

should be

    $dependencies = explode(',', $params['dependencies']);

**Comment by MrSwed** [comment]
i think too, but not shure

**Comment by Deesen** [comment]
Strange is, I have no issue using /install. Anyway I guess the problem is here. Maybe you want to remove these lines and test again on your side?

- https://github.com/modxcms/evolution/blob/develop/install/assets/modules/docmanager.tpl#L13
- https://github.com/modxcms/evolution/blob/develop/install/assets/modules/store.tpl#L12

**Comment by MrSwed** [comment]
my try was to update 1.0.5 to last (at that moment)

**Comment by Deesen** [comment]
Still issues with it?

**Comment by MrSwed** [comment]
@Deesen 
for simple update no longer noticed.
I think this is what need, thank you!

it remains to verify advanced update
